In [1]:
%load_ext autoreload
%autoreload 2

import pickle
import ujson
import json
import sys
import os
from collections import defaultdict

import pandas as pd
import numpy as np
import torch
import random
import faiss

from tqdm import tqdm
from collections import defaultdict
from typing import Optional

from bioel.utils.umls_utils import UmlsMappings
from bioel.utils.bigbio_utils import CUIS_TO_REMAP, CUIS_TO_EXCLUDE, DATASET_NAMES, VALIDATION_DOCUMENT_IDS
from bioel.utils.bigbio_utils import load_bigbio_dataset, add_deabbreviations, load_dataset_df, dataset_to_documents, dataset_to_df, load_dataset_df, resolve_abbreviation, dataset_unique_tax_ids
from bioel.utils.solve_abbreviation.solve_abbreviations import create_abbrev

from bioel.ontology import BiomedicalOntology
from bioel.models.arboel.biencoder.data.data_utils import process_ontology
from bioel.evaluate import Evaluate

from torch.utils.data import DataLoader

from peft import PeftModel
from transformers import AutoTokenizer
from vllm import LLM, SamplingParams
from ids import open_ai_api_key

/nethome/cye73/conda_envs/bioel/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

WARNING 09-22 11:13:12 cuda.py:22] You are using a deprecated `pynvml` package. Please install `nvidia-ml-py` instead, and make sure to uninstall `pynvml`. When both of them are installed, `pynvml` will take precedence and cause errors. See https://pypi.org/project/pynvml for more information.
WARNING 09-22 11:13:12 cuda.py:69] Detected different devices in the system:
WARNING 09-22 11:13:12 cuda.py:69] Tesla V100-PCIE-32GB
WARNING 09-22 11:13:12 cuda.py:69] NVIDIA A40
WARNING 09-22 11:13:12 cuda.py:69] NVIDIA A40
WARNING 09-22 11:13:12 cuda.py:69] NVIDIA A40
WARNING 09-22 11:13:12 cuda.py:69] Please make sure to set `CUDA_DEVICE_ORDER=PCI_BUS_ID` to avoid unexpected behavior.

2024-09-22 11:13:12,881	INFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.

In [2]:
from utils_functions import *

In [3]:
import openai
openai.api_key = open_ai_api_key
import re
import ujson
import logging
from collections import Counter, defaultdict
import pandas as pd

# Set up logging configuration
logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')
logging.getLogger("httpx").setLevel(logging.WARNING)
os.environ["CUDA_VISIBLE_DEVICES"] = "0,1" 
sampling_params = SamplingParams(temperature=0, top_p=0.9, max_tokens=1000, stop=["<|eot_id|>"])

In [4]:
# Check how many GPUs are visible
print(f"Visible GPUs: {torch.cuda.device_count()}")

# Check if you can access both GPUs
for i in range(torch.cuda.device_count()):
    print(f"GPU {i}: {torch.cuda.get_device_name(i)}")
    
device_1 = torch.device("cuda:0")  # First GPU (GPU 0)
device_2 = torch.device("cuda:1")  # Second GPU (GPU 1)

seed = 40
np.random.seed(seed)
random.seed(seed)

Visible GPUs: 2
GPU 0: NVIDIA A40
GPU 1: NVIDIA A40

In [5]:
ontology_dir = "/mitchell/entity-linking/kbs/medic.tsv"
name = "medic"
ontology2 = BiomedicalOntology.load_medic(filepath=ontology_dir, name=name)

# entrez_dict = {"name" : "entrez",
#              "filepath" : "/mitchell/entity-linking/el-robustness-comparison/data/gene_info.tsv",
#              "dataset" : "gnormplus",}
# ontology = BiomedicalOntology.load_entrez(**entrez_dict)

[2024-09-22 11:13:13] [ontology.py] [INFO] Reading entrez from /mitchell/entity-linking/kbs/medic.tsv

In [6]:
dataset_name = 'ncbi_disease'
# dataset_name = 'gnormplus'
path_to_abbrev = "/home2/cye73/data_test2/abbreviations.json"
dataset = load_bigbio_dataset(dataset_name)
dataset = add_deabbreviations(dataset, path_to_abbrev)

In [7]:
dataset_df = dataset_to_df(dataset)
test_df = dataset_df[dataset_df['split'] == 'test']
train_df = dataset_df[dataset_df['split'] == 'train']
test_df

,document_id,offsets,text,type,db_ids,split,deabbreviated_text,mention_id
5939,9288106,"[[40, 61]]",ataxia-telangiectasia,[Modifier],[MESH:D001260],test,ataxia-telangiectasia,9288106.1
5948,9288106,"[[72, 97]]",sporadic T-cell leukaemia,[SpecificDisease],[MESH:D015458],test,sporadic T-cell leukaemia,9288106.2
5949,9288106,"[[99, 120]]",Ataxia-telangiectasia,[SpecificDisease],[MESH:D001260],test,Ataxia-telangiectasia,9288106.3
5925,9288106,"[[122, 125]]",A-T,[SpecificDisease],[MESH:D001260],test,Ataxia-telangiectasia,9288106.4
5928,9288106,"[[132, 163]]",recessive multi-system disorder,[DiseaseClass],[MESH:D030342],test,recessive multi-system disorder,9288106.5
...,...,...,...,...,...,...,...,...
6880,9988281,"[[996, 1015]]",breast malignancies,[SpecificDisease],[MESH:D001943],test,breast malignancies,9988281.7
6870,9988281,"[[1123, 1147]]",invasive lobular cancers,[DiseaseClass],[MESH:D018275],test,invasive lobular cancers,9988281.8
6871,9988281,"[[1152, 1179]]",low-grade ductal carcinomas,[SpecificDisease],[MESH:D044584],test,low-grade ductal carcinomas,9988281.9
6873,9988281,"[[1269, 1286]]",ductal carcinomas,[SpecificDisease],[MESH:D044584],test,ductal carcinomas,9988281.10
6874,9988281,"[[1387, 1410]]",sporadic breast cancers,[SpecificDisease],[MESH:D001943],test,sporadic breast cancers,9988281.11

In [8]:
docs = dataset_to_documents(dataset)
# docs

In [9]:
add_full_context(df = test_df, docs=docs)
add_full_context(df = train_df, docs=docs)
# test_df

/home2/cye73/llm_disambiguator/experiments/utils_functions.py:276: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["contextualized_mention"] = contextualized_mentions
/home2/cye73/llm_disambiguator/experiments/utils_functions.py:276: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["contextualized_mention"] = contextualized_mentions

In [10]:
_, TestMap_mention2context = add_context(df = test_df, docs = docs)
corpus, TrainMap_mention2context = add_context(df = train_df, docs = docs)
_, _ = add_context(df = dataset_df, docs = docs)
# dataset_df

/home2/cye73/llm_disambiguator/experiments/utils_functions.py:322: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["limited_contextualized_mention"] = limited_contextualized_mentions
/home2/cye73/llm_disambiguator/experiments/utils_functions.py:322: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["limited_contextualized_mention"] = limited_contextualized_mentions

In [11]:
# TrainMap_mention2context
# print(len(corpus))

In [12]:
# # # Load a pre-trained SentenceBERT model
# # model = SentenceTransformer('sentence-transformers/all-mpnet-base-v2')

# # # Generate embeddings for the corpus
# # corpus_embeddings = model.encode(corpus, convert_to_tensor=True)

# from sentence_transformers import SentenceTransformer
# model = SentenceTransformer('princeton-nlp/sup-simcse-bert-base-uncased')
# model.to(device_1)
# # Generate embeddings for the corpus
# corpus_embeddings = model.encode(corpus, convert_to_tensor=True)

# corpus_embeddings = corpus_embeddings.cpu().detach().numpy()

In [13]:
# embedding_dimension = corpus_embeddings.shape[1]

# # Create the HNSW index with the correct arguments
# M = 32  # Number of neighbors in the HNSW graph
# index = faiss.IndexHNSWFlat(embedding_dimension, M)

# # Normalize the corpus embeddings if using cosine similarity
# faiss.normalize_L2(corpus_embeddings)

# # Add the embeddings to the index
# index.add(corpus_embeddings)

# # Print the number of sentences added to the index
# print(f"Number of sentences in the index: {index.ntotal}")

In [14]:
# def knn_query(model, index, query, k=5):
#     ''' 
#     Find the top k most similar embeddings of the query from the corpus.
#     ------
#     model : SentenceTransformer model
#     index : faiss index
#     query : str (mention + surrounding context)
#     k : int (number of similar embeddings to find)
#     '''
#     # Generate embedding for the query
#     query_embedding = model.encode(query, convert_to_tensor=True).cpu().detach().numpy()
#     query_embedding = query_embedding.reshape(1, -1)
#     print(query_embedding.shape)
#     # Normalize the query embedding for cosine similarity
#     faiss.normalize_L2(query_embedding)
    
#     # Perform the search
#     distances, indices = index.search(query_embedding, k)
    
#     # print("Query:", TestMap_cui2context[query])
#     # print("\nTop 3 most similar sentences in the corpus:")
    
#     # for i, idxs in enumerate(indices[0]):
#     #     print(f"{i+1}. {corpus[idxs]} (Distance: {distances[0][i]})")
    
#     return indices[0]

In [15]:
TrainMap_context2mention = {v: k for k, v in TrainMap_mention2context.items()}
# TrainMap_context2mention

# Load arboel results

In [16]:
dataset_names = ["ncbi_disease"]
model_names = ["arboel_biencoder", "arboel_crossencoder"]
path_to_result = {"ncbi_disease": {
        "arboel_biencoder": "/home2/cye73/results2/arboel/ncbi_disease/biencoder_output_eval.json",
        "arboel_crossencoder": "/home2/cye73/results2/arboel/ncbi_disease/crossencoder_output_eval.json"
    }}

# dataset_names = ["gnormplus"]
# model_names = ["arboel_biencoder", "arboel_crossencoder"]
# path_to_result = {"gnormplus": {
#         "arboel_biencoder": "/home2/cye73/results2/arboel/gnormplus/biencoder_output_eval.json",
#         "arboel_crossencoder": "/home2/cye73/results2/arboel/gnormplus/crossencoder_output_eval.json"
#     }}

abbreviations_path = "/home2/cye73/data_test/abbreviations.json"

evaluator = Evaluate(dataset_names, model_names, path_to_result,
                     abbreviations_path
                     )
evaluator.load_results()
evaluator.process_datasets()
evaluator.evaluate(
    eval_strategies=['basic']
                   )
# evaluator.plot_results(
#     # eval_strategies=['basic']
#     )

dataset : ncbi_disease, model : arboel_biencoder
dataset : ncbi_disease, model : arboel_crossencoder

  0%|          | 0/1 [00:00<?, ?it/s]

Eval Strategy: basic
ncbi_disease

/home2/cye73/biomedical-entity-linking/bioel/bioel/evaluate.py:249: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  lambda x: min_hit_index(x[0], x[1], eval_mode=eval_mode), axis=1
/home2/cye73/biomedical-entity-linking/bioel/bioel/evaluate.py:249: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  lambda x: min_hit_index(x[0], x[1], eval_mode=eval_mode), axis=1
/home2/cye73/biomedical-entity-linking/bioel/bioel/evaluate.py:249: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  lambda x: min_hit_index(x[0], x[1], eval_mode=eval_mode), axis=1
/home2/cye73/biomedical-entity-linking/bioel/bioel/evaluate.py:249: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  lambda x: min_hit_index(x[0], x[1], eval_mode=eval_mode), axis=1
100%|██████████| 1/1 [00:00<00:00,  6.14it/s]

In [23]:
number_candidates = 64

# results = evaluator.full_results["basic"]["gnormplus"]
results = evaluator.full_results["basic"]["ncbi_disease"]
results
cols = ['document_id', 'offsets', 'deabbreviated_text', 'db_ids', 'mention_id', 'joined_offsets', 'arboel_biencoder_resolve_abbrev', 'arboel_biencoder_resolve_abbrev_min_hit_index', 'arboel_crossencoder_resolve_abbrev', 'arboel_crossencoder_resolve_abbrev_min_hit_index']
filtered_results = results[cols].rename(columns={'arboel_biencoder_resolve_abbrev': 'biencoder_candidates',
                                                 'arboel_crossencoder_resolve_abbrev': 'crossencoder_candidates',
                                                 'arboel_biencoder_resolve_abbrev_min_hit_index': 'biencoder_hit_index',
                                                 'arboel_crossencoder_resolve_abbrev_min_hit_index': 'crossencoder_hit_index'})

filtered_results = filtered_results[filtered_results['crossencoder_hit_index'] < number_candidates]
# filtered_results = filtered_results[filtered_results['crossencoder_hit_index'] < 50]

# filtered_results = filtered_results[filtered_results['crossencoder_candidates'].apply(lambda x: len(x[0]) != 0 if x else False)]

# filtered_results = filtered_results.iloc[:500]
filtered_results

,document_id,offsets,deabbreviated_text,db_ids,mention_id,joined_offsets,biencoder_candidates,biencoder_hit_index,crossencoder_candidates,crossencoder_hit_index
0,9288106,"[[40, 61]]",ataxia-telangiectasia,[MESH:D001260],9288106.1,"40,61","[[MESH:D001260, OMIM:208900], [MESH:D057891], ...",0,"[[MESH:D001260, OMIM:208900], [MESH:D057891], ...",0
2,9288106,"[[99, 120]]",Ataxia-telangiectasia,[MESH:D001260],9288106.3,"99,120","[[MESH:D001260, OMIM:208900], [MESH:D057891], ...",0,"[[MESH:D001260, OMIM:208900], [MESH:D057891], ...",0
3,9288106,"[[122, 125]]",Ataxia-telangiectasia,[MESH:D001260],9288106.4,"122,125","[[MESH:D001260, OMIM:208900], [MESH:D019294, O...",0,"[[MESH:D001260, OMIM:208900], [MESH:C566865], ...",0
4,9288106,"[[132, 163]]",recessive multi-system disorder,[MESH:D030342],9288106.5,"132,163","[[MESH:D030342], [MESH:D004194], [MESH:D001523...",0,"[[MESH:D030342], [MESH:D058495, OMIM:117550], ...",0
5,9288106,"[[235, 241]]",cancer,[MESH:D009369],9288106.6,"235,241","[[MESH:D009369], [MESH:D018198], [MESH:D002471...",0,"[[MESH:D009369], [MESH:D002277], [MESH:D009386...",0
...,...,...,...,...,...,...,...,...,...,...
955,9988281,"[[996, 1015]]",breast malignancies,[MESH:D001943],9988281.7,"996,1015","[[MESH:D001943, OMIM:114480], [MESH:D058922], ...",0,"[[MESH:D001943, OMIM:114480], [MESH:D009369], ...",0
956,9988281,"[[1123, 1147]]",invasive lobular cancers,[MESH:D018275],9988281.8,"1123,1147","[[MESH:D018275], [MESH:D018299], [MESH:D009369...",0,"[[MESH:D018275], [MESH:D009369], [MESH:D002277...",0
957,9988281,"[[1152, 1179]]",low-grade ductal carcinomas,[MESH:D044584],9988281.9,"1152,1179","[[MESH:D044584], [MESH:D018270], [MESH:D002277...",0,"[[MESH:D044584], [MESH:D018270], [MESH:D002277...",0
958,9988281,"[[1269, 1286]]",ductal carcinomas,[MESH:D044584],9988281.10,"1269,1286","[[MESH:D044584], [MESH:D018270], [MESH:D002277...",0,"[[MESH:D044584], [MESH:D018270], [MESH:D002292...",0
959,9988281,"[[1387, 1410]]",sporadic breast cancers,[MESH:D001943],9988281.11,"1387,1410","[[MESH:D001943, OMIM:114480], [MESH:D061325], ...",0,"[[MESH:D001943, OMIM:114480], [MESH:D009369], ...",0

In [24]:
total_nb_mentions = len(results)
total_nb_mentions

960

In [25]:
# def number_hit(df, hit_index_column, hit_range):
#     ''' 
#     Count the number of hits for each hit index.
#     ------
#     df : DataFrame
#     hit_index_column : str (column name of the hit index)
#     hit_range : int (Number of hits to consider = recall@k)
#     '''
#     results = {i+1: 0 for i in range(hit_range)}
#     res = 0
#     for hit_index in range(hit_range):
#         for idx, row in df.iterrows():
#             if row[hit_index_column] == hit_index:
#                 res += 1
#         results[hit_index+1] = res
#     return results

number_hits_biencoder = number_hit(filtered_results, 'biencoder_hit_index', number_candidates)
number_hits_crossencoder = number_hit(filtered_results, 'crossencoder_hit_index', number_candidates)

In [26]:
# print('number hits biencoder :')
# number_hits_biencoder
print('number hits crossencoder :')
number_hits_crossencoder

number hits crossencoder :

{1: 740,
 2: 767,
 3: 775,
 4: 785,
 5: 787,
 6: 791,
 7: 793,
 8: 796,
 9: 797,
 10: 799,
 11: 800,
 12: 801,
 13: 802,
 14: 803,
 15: 803,
 16: 803,
 17: 803,
 18: 803,
 19: 804,
 20: 804,
 21: 807,
 22: 807,
 23: 808,
 24: 808,
 25: 808,
 26: 808,
 27: 808,
 28: 809,
 29: 809,
 30: 809,
 31: 809,
 32: 809,
 33: 809,
 34: 809,
 35: 809,
 36: 809,
 37: 809,
 38: 809,
 39: 809,
 40: 809,
 41: 809,
 42: 809,
 43: 809,
 44: 809,
 45: 809,
 46: 809,
 47: 809,
 48: 809,
 49: 809,
 50: 809,
 51: 809,
 52: 809,
 53: 809,
 54: 809,
 55: 809,
 56: 809,
 57: 809,
 58: 809,
 59: 809,
 60: 809,
 61: 809,
 62: 809,
 63: 809,
 64: 809}

In [27]:
# def compute_recall(df, hit_index_column, hit_range, total_nb_mentions):
#     ''' 
#     Function to compute the recall of the intial model (biencoder, crossencoder).
#     ------
#     df : DataFrame
#     hit_index_column : str ("biencoder_hit_index" or "crossencoder_hit_index")
#     hit_range : int (Number of hits to consider = recall@k)
#     total_nb_mentions : int (For unnormalized result = true performance)
#     '''
#     unnormalized_recall = 0
#     normalized_recall = 0
#     results = []
    
#     for hit_index in range(hit_range):
#         res = 0
#         for idx, row in df.iterrows():
#             if row[hit_index_column] == hit_index:
#                 res += 1
#         unnormalized_recall += res / total_nb_mentions
#         normalized_recall += res / len(df)

#         # Store the cumulative results for this hit_index
#         results.append((unnormalized_recall, normalized_recall))
    
#     return results

biencoder_results = compute_recall(filtered_results, "biencoder_hit_index", 5, total_nb_mentions)
print("Biencoder:")
for i, (unnormalized, normalized) in enumerate(biencoder_results):
    print(f"recall {i+1}: Normalized = {normalized:.4f}, Unnormalized = {unnormalized:.4f}")

crossencoder_results = compute_recall(filtered_results, "crossencoder_hit_index", 5, total_nb_mentions)
print("Crossencoder:")
for i, (unnormalized, normalized) in enumerate(crossencoder_results):
    print(f"recall {i+1}: Normalized = {normalized:.4f}, Unnormalized = {unnormalized:.4f}")

Biencoder:
recall 1: Normalized = 0.8714, Unnormalized = 0.7344
recall 2: Normalized = 0.9159, Unnormalized = 0.7719
recall 3: Normalized = 0.9333, Unnormalized = 0.7865
recall 4: Normalized = 0.9431, Unnormalized = 0.7948
recall 5: Normalized = 0.9481, Unnormalized = 0.7990
Crossencoder:
recall 1: Normalized = 0.9147, Unnormalized = 0.7708
recall 2: Normalized = 0.9481, Unnormalized = 0.7990
recall 3: Normalized = 0.9580, Unnormalized = 0.8073
recall 4: Normalized = 0.9703, Unnormalized = 0.8177
recall 5: Normalized = 0.9728, Unnormalized = 0.8198

# Part with GPT

### Train set

In [22]:

train_mentions = []
train_mention2context = {}
train_mention2gold = {}
train_mention2text = {}
for idx, row in train_df.iterrows():
    train_mention2gold[row['mention_id']] = row['db_ids']
    train_mentions.append(row['mention_id'])
    train_mention2text[row['mention_id']] = row['deabbreviated_text']
    train_mention2context[row["mention_id"]] = row["limited_contextualized_mention"]

# train_mention2gold

### Test set

In [23]:
mention2context = {}
for idx, row in test_df.iterrows():
    mention2context[row["mention_id"]] = row["limited_contextualized_mention"]

mentions = []
mention2biencoder_candidates = {}
mention2crossencoder_candidates = {}
mention2gold = {}
mention2hit = {}
mention2text = {}
for idx, row in filtered_results.iterrows():
    # print(idx)
    # Only consider row if hit_index < max number of candidates
    if row['biencoder_hit_index'] < number_candidates:
        mention2biencoder_candidates[row['mention_id']] = [el[0] for el in row['biencoder_candidates'][:number_candidates]]
        # mention2crossencoder_candidates[row['mention_id']] = [el[0] for el in row['crossencoder_candidates'][:number_candidates]]
        mention2gold[row['mention_id']] = row['db_ids']
        mentions.append(row['mention_id'])
        mention2text[row['mention_id']] = row['deabbreviated_text']
        mention2hit[row['mention_id']] = row['biencoder_hit_index']
print(len(mention2hit))
mention2hit
# len(test_df)

817

{'9288106.1': 0,
 '9288106.2': 1,
 '9288106.3': 0,
 '9288106.4': 0,
 '9288106.5': 0,
 '9288106.6': 0,
 '9288106.7': 0,
 '9288106.8': 0,
 '9288106.9': 0,
 '9288106.10': 1,
 '9288106.11': 0,
 '9288106.12': 43,
 '9288106.13': 1,
 '9288106.14': 0,
 '9288106.15': 0,
 '9288106.16': 0,
 '9288106.17': 0,
 '9288106.18': 0,
 '9288106.19': 0,
 '9288106.20': 0,
 '9288106.21': 0,
 '9288106.22': 0,
 '9288106.23': 2,
 '9288106.24': 2,
 '9288106.25': 2,
 '9288106.26': 0,
 '9288106.28': 0,
 '9288106.29': 1,
 '9294109.1': 0,
 '9294109.2': 0,
 '9294109.3': 0,
 '9294109.4': 1,
 '9294109.5': 0,
 '9311732.1': 0,
 '9311732.2': 0,
 '9311732.3': 0,
 '9311732.4': 0,
 '9311732.5': 0,
 '9311732.6': 0,
 '9311732.7': 0,
 '9311732.8': 0,
 '9311732.9': 0,
 '9311732.10': 0,
 '9311732.11': 0,
 '9311732.12': 0,
 '9311732.13': 0,
 '9311732.14': 0,
 '9311732.15': 0,
 '932197.3': 0,
 '932197.9': 0,
 '932197.10': 0,
 '932197.11': 0,
 '932197.12': 0,
 '932197.14': 0,
 '9336417.1': 0,
 '9336417.2': 0,
 '9336417.3': 0,
 '9336417.4': 0,
 '9336417.5': 0,
 '9336417.6': 0,
 '9336417.7': 0,
 '9336417.8': 0,
 '9342365.1': 0,
 '9342365.2': 0,
 '9342365.3': 0,
 '9358014.1': 0,
 '9358014.2': 0,
 '9358014.3': 0,
 '9358014.4': 0,
 '9358014.5': 0,
 '9360520.4': 0,
 '9360520.5': 0,
 '9360520.7': 0,
 '9371490.1': 0,
 '9371490.2': 2,
 '9371490.3': 3,
 '9371490.4': 0,
 '9371490.5': 0,
 '9371490.6': 0,
 '9371490.7': 0,
 '9371490.8': 0,
 '9371490.9': 0,
 '9371490.10': 0,
 '9382108.1': 0,
 '9382108.2': 0,
 '9382108.3': 0,
 '9382108.4': 0,
 '9382108.5': 0,
 '9385378.4': 0,
 '9385378.5': 0,
 '9391879.1': 0,
 '9391879.2': 0,
 '9391879.3': 0,
 '9391879.4': 0,
 '9391879.5': 0,
 '9391889.1': 0,
 '9391889.2': 0,
 '9391889.3': 0,
 '9391889.4': 0,
 '9391889.5': 0,
 '9391889.6': 0,
 '9391889.7': 0,
 '9391889.8': 0,
 '9391889.9': 0,
 '9391889.10': 0,
 '9391889.11': 0,
 '9391889.12': 0,
 '9391889.13': 1,
 '9391889.14': 0,
 '9400934.1': 0,
 '9400934.2': 0,
 '9400934.3': 0,
 '9400934.4': 0,
 '9400934.5': 0,
 '941901.1': 0,
 '941901.2': 0,
 '941901.3': 0,
 '941901.4': 0,
 '941901.5': 0,
 '941901.6': 0,
 '941901.7': 0,
 '941901.8': 43,
 '9420335.1': 0,
 '9420335.2': 0,
 '9420335.3': 0,
 '9420335.4': 1,
 '9425228.1': 0,
 '9425228.2': 0,
 '9425228.3': 0,
 '9425228.4': 0,
 '9425228.5': 0,
 '9425228.6': 0,
 '9425239.1': 0,
 '9425239.2': 0,
 '9425239.3': 0,
 '9425239.4': 0,
 '9425239.5': 0,
 '9425239.6': 0,
 '9425239.7': 0,
 '9427148.1': 0,
 '9427148.2': 0,
 '9427148.3': 0,
 '9427148.4': 0,
 '9427148.5': 0,
 '9427148.6': 0,
 '9427148.7': 0,
 '9427148.8': 0,
 '9439660.1': 0,
 '9439660.2': 0,
 '9439660.3': 0,
 '9439660.4': 0,
 '9439660.5': 1,
 '9439660.6': 0,
 '9439660.7': 0,
 '9439660.8': 0,
 '9439660.9': 0,
 '9439660.10': 0,
 '9439660.11': 0,
 '9439660.12': 1,
 '9439660.13': 0,
 '9443866.1': 0,
 '9443866.2': 0,
 '9443866.3': 0,
 '9443866.4': 0,
 '9443866.5': 0,
 '9448273.1': 0,
 '9448273.2': 0,
 '9448273.3': 0,
 '9448273.4': 0,
 '9448273.5': 0,
 '9448273.6': 0,
 '9448273.7': 0,
 '9448273.8': 0,
 '9448273.9': 0,
 '9448273.10': 0,
 '9448273.11': 62,
 '9448273.12': 0,
 '9448273.13': 0,
 '9448273.14': 0,
 '9448273.15': 0,
 '9448273.16': 0,
 '9448273.17': 0,
 '9448273.18': 0,
 '9450866.1': 0,
 '9450866.2': 0,
 '9450866.3': 0,
 '9450866.4': 0,
 '9450866.5': 1,
 '9450866.6': 0,
 '9450866.7': 0,
 '9450866.8': 0,
 '9450866.9': 0,
 '9450866.10': 0,
 '9450866.11': 0,
 '9457914.3': 0,
 '9457914.4': 0,
 '9457914.5': 16,
 '9457914.6': 3,
 '9457914.7': 0,
 '9457914.8': 19,
 '9463309.1': 52,
 '9463309.2': 52,
 '9463309.3': 13,
 '9463309.4': 63,
 '9463309.7': 38,
 '9463314.1': 0,
 '9463314.2': 0,
 '9463314.3': 0,
 '9463314.4': 0,
 '9463314.5': 0,
 '9463314.6': 0,
 '9463314.7': 1,
 '9463314.8': 0,
 '9463314.9': 0,
 '9463314.10': 0,
 '9463314.11': 1,
 '9463314.12': 0,
 '9463314.13': 0,
 '9463314.14': 0,
 '9463314.15': 0,
 '9463314.16': 0,
 '9463318.1': 0,
 '9463318.2': 0,
 '9465039.1': 0,
 '9465039.2': 0,
 '9465039.3': 0,
 '9465301.1': 0,
 '9465301.2': 0,
 '9467011.3': 15,
 '9467011.4': 0,
 '9467011.5': 1,
 '9467011.6': 0,
 '9467011.7': 0,
 '9467011.8': 0,
 '9467011.9': 0,
 '9467011.10': 0,
 '9467011.11': 7,
 '9467011.26': 2,
 '9467011.27': 3,
 '9472666.4': 0,
 '9472666.6': 0,
 '9472666.7': 0,
 '9482572.1': 0,
 '9482572.2': 0,
 '9482572.3': 0,
 '9482572.4': 0,
 '9482572.6': 0,
 '9497246.1': 0,
 '9497246.2': 0,
 '9497246.3': 3,
 '9497246.4': 0,
 '9497246.5': 0,
 '9497246.6': 0,
 '9497246.7': 0,
 '9497246.8': 0,
 '9497246.9': 0,
 '9497246.10': 0,
 '9497246.11': 0,
 '9497246.12': 0,
 '9506545.1': 0,
 '9506545.2': 3,
 '9506545.3': 4,
 '9506545.7': 0,
 '9506545.8': 0,
 '9506545.9': 0,
 '9506545.13': 0,
 '9506545.14': 0,
 '9506545.15': 1,
 '9506545.18': 0,
 '9506545.21': 0,
 '9521325.1': 0,
 '9521325.2': 3,
 '9521325.3': 0,
 '9521325.4': 0,
 '9521325.5': 0,
 '9521325.6': 0,
 '9521325.7': 0,
 '9521325.8': 0,
 '9521325.9': 0,
 '9521325.10': 0,
 '9521421.4': 0,
 '9521421.5': 0,
 '9529364.1': 0,
 '9529364.2': 0,
 '9529364.3': 0,
 '9529364.4': 0,
 '9529364.5': 0,
 '9529364.6': 0,
 '9529364.7': 0,
 '9529364.8': 0,
 '9529364.9': 0,
 '9529364.12': 0,
 '9529364.13': 0,
 '9529364.14': 0,
 '9529364.18': 0,
 '9529364.20': 0,
 '9529364.21': 0,
 '9536083.1': 16,
 '9536083.2': 0,
 '9546397.1': 0,
 '9546397.2': 0,
 '9546397.3': 0,
 '9546397.4': 0,
 '9554743.1': 0,
 '9554743.2': 0,
 '9554743.3': 0,
 '9563950.1': 0,
 '9563950.2': 0,
 '9563950.3': 0,
 '9563950.4': 0,
 '9563950.5': 0,
 '9563950.6': 0,
 '9563950.7': 0,
 '9580132.4': 0,
 '9585583.3': 0,
 '9585583.4': 6,
 '9585583.5': 0,
 '9585583.10': 0,
 '9585583.11': 1,
 '9585583.12': 0,
 '9585583.13': 27,
 '9585583.15': 6,
 '9585605.1': 0,
 '9585605.2': 0,
 '9585605.3': 0,
 '9585605.4': 0,
 '9585605.5': 0,
 '9585605.6': 0,
 '9585605.7': 0,
 '9585605.8': 0,
 '9585605.9': 0,
 '9585606.1': 0,
 '9585606.2': 0,
 '9585606.3': 0,
 '9585606.4': 0,
 '9585606.5': 0,
 '9585606.6': 0,
 '9585606.7': 0,
 '9585611.2': 0,
 '9585611.3': 12,
 '9585611.4': 0,
 '9585611.5': 0,
 '9585611.6': 0,
 '9585611.7': 0,
 '9585611.8': 15,
 '9585611.9': 0,
 '9585611.10': 3,
 '9585611.11': 0,
 '9585611.12': 0,
 '9585611.13': 0,
 '9585611.14': 0,
 '9585611.16': 0,
 '9585611.17': 48,
 '9585611.19': 49,
 '9585611.20': 4,
 '9585611.22': 0,
 '9585611.23': 0,
 '9590178.1': 0,
 '9590178.2': 0,
 '9590178.3': 16,
 '9590178.4': 0,
 '9590284.1': 0,
 '9590284.2': 0,
 '9590284.3': 0,
 '9590284.4': 0,
 '9590284.5': 0,
 '9590284.6': 0,
 '9600235.1': 0,
 '9600235.2': 0,
 '9600235.3': 0,
 '9600235.4': 0,
 '9600235.5': 0,
 '9600235.6': 0,
 '9603435.1': 1,
 '9603435.2': 0,
 '9603435.3': 0,
 '9603435.5': 0,
 '9603435.6': 0,
 '9603435.8': 63,
 '9618166.1': 0,
 '9618166.2': 0,
 '9618166.3': 0,
 '9618166.4': 0,
 '9618166.5': 0,
 '9618166.6': 0,
 '9618166.7': 0,
 '9618166.8': 0,
 '9618166.9': 0,
 '9618166.10': 0,
 '9618170.1': 0,
 '9618170.2': 5,
 '9618170.3': 29,
 '9618170.4': 4,
 '9618170.5': 2,
 '9618170.6': 19,
 '9618170.7': 0,
 '9618170.8': 0,
 '9618170.9': 2,
 '9618170.10': 2,
 '9618170.11': 2,
 '9618170.12': 2,
 '9620771.1': 0,
 '9620771.2': 0,
 '9620771.3': 26,
 '9620771.4': 0,
 '9620771.5': 0,
 '9620771.6': 0,
 '9620771.8': 0,
 '9620771.9': 0,
 '9620771.10': 0,
 '9620771.11': 0,
 '9634518.2': 0,
 '9634518.3': 0,
 '9634518.4': 0,
 '9634518.5': 0,
 '9634518.6': 0,
 '9634518.9': 0,
 '9668171.1': 0,
 '9668171.2': 0,
 '9668171.3': 0,
 '9668171.4': 0,
 '9668171.5': 0,
 '9668171.6': 0,
 '9668171.7': 0,
 '9671401.1': 0,
 '9671401.2': 0,
 '9671401.3': 0,
 '9671401.4': 0,
 '9671401.5': 0,
 '9674903.1': 0,
 '9674903.2': 0,
 '9674903.3': 1,
 '9674903.4': 0,
 '9674903.5': 0,
 '9674903.6': 1,
 '9674903.7': 0,
 '9674903.8': 0,
 '9674903.9': 0,
 '9674903.10': 0,
 '9674903.11': 0,
 '9674903.12': 0,
 '9674903.13': 0,
 '9674903.14': 1,
 '9674903.15': 0,
 '9674906.1': 4,
 '9674906.2': 0,
 '9674906.5': 0,
 '9674906.6': 15,
 '9674906.8': 0,
 '9674906.9': 0,
 '9674906.10': 5,
 '9674906.11': 14,
 '9674906.12': 0,
 '9674906.13': 1,
 '9674906.15': 0,
 '9674906.17': 0,
 '9674906.18': 0,
 '9674906.19': 0,
 '9674906.21': 0,
 '9674906.22': 6,
 '9674906.24': 0,
 '9674906.25': 0,
 '9689113.1': 0,
 '9689113.2': 0,
 '9689113.3': 9,
 '9689113.4': 0,
 '9689113.5': 13,
 '9689113.6': 0,
 '9689113.7': 0,
 '9689113.8': 0,
 '9689113.9': 0,
 '9700175.1': 0,
 '9700175.2': 0,
 '9700175.3': 0,
 '9700175.4': 0,
 '9700175.5': 0,
 '9700175.6': 0,
 '9700175.7': 0,
 '9700175.8': 0,
 '9700175.9': 0,
 '9702690.1': 0,
 '9702690.2': 0,
 '9702690.3': 0,
 '9702690.4': 0,
 '9702690.5': 0,
 '9702690.6': 0,
 '9702690.7': 0,
 '9702690.8': 0,
 '9702690.9': 1,
 '9702690.10': 0,
 '9702690.11': 0,
 '9702690.12': 0,
 '9702690.13': 0,
 '9702690.14': 0,
 '9703418.3': 0,
 '9703418.6': 0,
 '9703501.1': 0,
 '9703501.2': 0,
 '9705283.1': 0,
 '9705283.2': 0,
 '9705283.3': 0,
 '9705283.5': 0,
 '9705283.6': 0,
 '9705283.7': 0,
 '9709714.1': 0,
 '9709714.2': 0,
 '9709714.3': 0,
 '9709714.4': 0,
 '9709714.5': 0,
 '9709714.6': 0,
 '9709714.7': 31,
 '9709714.8': 0,
 '9709714.9': 0,
 '9709714.10': 0,
 '9709714.11': 0,
 '9714764.1': 2,
 '9714764.2': 2,
 '9714764.3': 0,
 '9724771.1': 0,
 '9724771.2': 0,
 '9724771.3': 0,
 '9724771.4': 0,
 '9724771.5': 0,
 '9724771.6': 1,
 '9724771.7': 0,
 '9724771.8': 0,
 '9724771.9': 1,
 '9724771.10': 0,
 '9724771.11': 0,
 '9724771.12': 0,
 '9724771.13': 0,
 '9724771.14': 0,
 '9724771.15': 0,
 '9724771.16': 0,
 '9724771.17': 0,
 '9724771.18': 0,
 '9724771.19': 1,
 '9724771.20': 0,
 '9724771.22': 0,
 '9724771.23': 1,
 '9724771.24': 0,
 '9724771.25': 0,
 '9729124.1': 0,
 '9729124.2': 0,
 '9729124.3': 0,
 '9729124.4': 0,
 '9729124.5': 0,
 '9729124.6': 0,
 '9729124.7': 0,
 '9729124.8': 0,
 '9729124.9': 0,
 '9731533.1': 0,
 '9731533.2': 0,
 '9731533.3': 0,
 '9731533.4': 0,
 '9731533.5': 1,
 '9731533.6': 0,
 '9731533.7': 0,
 '9731533.8': 0,
 '9731533.9': 0,
 '9731533.10': 0,
 '9731533.11': 0,
 '9731533.12': 0,
 '9733027.1': 0,
 '9733027.2': 0,
 '9733027.3': 0,
 '9733027.4': 0,
 '9744473.1': 0,
 '9744473.2': 0,
 '9744473.3': 0,
 '9744473.4': 0,
 '9744473.5': 0,
 '9744473.6': 0,
 '9744473.7': 0,
 '9770531.1': 0,
 '9770531.2': 0,
 '9770531.3': 0,
 '9770531.4': 0,
 '9770531.5': 0,
 '9770531.6': 0,
 '9770531.7': 0,
 '9770531.8': 0,
 '9770531.9': 0,
 '9770531.10': 0,
 '9771706.1': 0,
 '9771706.2': 0,
 '9771706.6': 0,
 '9771706.7': 1,
 '9771706.8': 0,
 '9774970.1': 0,
 '9774970.2': 0,
 '9774970.3': 0,
 '9790667.1': 0,
 '9790667.2': 0,
 '9792409.1': 0,
 '9792409.2': 0,
 '9792409.3': 0,
 '9792409.4': 0,
 '9792409.5': 0,
 '9792409.6': 0,
 '9792409.7': 0,
 '9792409.8': 0,
 '9792860.1': 36,
 '9792860.2': 14,
 '9792860.3': 1,
 '9792860.4': 1,
 '9792860.5': 34,
 '9792861.1': 0,
 '9792861.2': 0,
 '9792861.3': 0,
 '9792861.4': 0,
 '9792861.5': 0,
 '9792861.6': 0,
 '9792861.7': 0,
 '9792861.8': 0,
 '9792861.9': 0,
 '9792861.10': 0,
 '9800909.1': 0,
 '9800909.2': 0,
 '9800909.3': 0,
 '9800909.4': 0,
 '9800909.5': 0,
 '9800909.6': 0,
 '9800909.7': 0,
 '9800909.8': 0,
 '9800909.9': 1,
 '9800909.10': 0,
 '9800909.11': 0,
 '9800909.12': 0,
 '9831355.1': 0,
 '9831355.2': 0,
 '9831355.3': 0,
 '9831355.4': 0,
 '9831355.5': 0,
 '9843038.1': 0,
 '9843038.2': 0,
 '9843038.3': 0,
 '9843038.4': 0,
 '9843038.5': 9,
 '9843038.6': 0,
 '9848786.2': 7,
 '9848786.4': 0,
 '9848786.5': 7,
 '9848786.6': 9,
 '9848786.8': 0,
 '9848786.9': 1,
 '9848786.10': 0,
 '9852676.1': 0,
 '9852676.2': 0,
 '9852676.3': 0,
 '9852676.4': 0,
 '9852676.5': 0,
 '9852676.6': 0,
 '9852676.7': 0,
 '9852676.8': 0,
 '9852676.9': 0,
 '9852676.10': 0,
 '9856498.3': 0,
 '9861003.1': 0,
 '9861003.2': 0,
 '9861003.3': 0,
 '9861003.4': 9,
 '9861003.7': 0,
 '9861003.8': 0,
 '9861003.9': 0,
 '9861003.10': 0,
 '9861003.11': 0,
 '9861003.12': 0,
 '9861003.13': 0,
 '9861003.14': 0,
 '9861003.15': 0,
 '9863607.1': 0,
 '9863607.2': 0,
 '9863607.3': 0,
 '9863607.4': 0,
 '9863607.5': 0,
 '9863607.6': 0,
 '9863607.7': 3,
 '9863607.8': 0,
 '9863607.9': 0,
 '9863607.10': 0,
 '9863607.11': 0,
 '9863607.12': 0,
 '9863607.13': 0,
 '9863607.14': 0,
 '9863607.15': 0,
 '9867744.1': 0,
 '9867744.2': 0,
 '9867744.3': 0,
 '9867744.4': 0,
 '9867744.5': 0,
 '9867744.6': 0,
 '9867744.7': 0,
 '9867744.8': 0,
 '9867744.9': 0,
 '9869602.1': 0,
 '9869602.2': 0,
 '9869602.3': 0,
 '9869602.4': 0,
 '9869602.5': 0,
 '9869602.6': 0,
 '9869602.7': 0,
 '9869602.8': 0,
 '9869602.9': 0,
 '9869602.10': 0,
 '9869602.11': 0,
 '9869602.12': 0,
 '9869602.13': 0,
 '9869602.14': 0,
 '9888388.1': 1,
 '9888388.2': 1,
 '9888388.3': 1,
 '9888388.4': 0,
 '9888388.6': 1,
 '9888388.7': 0,
 '9888388.8': 0,
 '9888388.9': 0,
 '9888388.10': 48,
 '9888390.1': 0,
 '9888390.2': 0,
 '9888390.3': 0,
 '9888390.4': 0,
 '9888390.5': 0,
 '9888390.6': 0,
 '9888390.7': 0,
 '9927033.1': 0,
 '9927033.2': 0,
 '9927033.3': 0,
 '9927033.4': 0,
 '9927033.5': 0,
 '9927033.6': 0,
 '9927033.7': 0,
 '9927033.8': 0,
 '9927033.9': 0,
 '9927033.10': 2,
 '9931324.1': 0,
 '9931324.2': 0,
 '9931324.3': 0,
 '9931324.4': 0,
 '9931324.5': 0,
 '9931324.6': 0,
 '9931324.7': 0,
 '9931324.8': 0,
 '9931324.9': 7,
 '9931324.10': 1,
 '9931324.12': 0,
 '993342.1': 0,
 '993342.2': 0,
 '993342.3': 0,
 '993342.4': 0,
 '993342.5': 0,
 '993342.6': 0,
 '993342.7': 0,
 '993342.8': 0,
 '993342.9': 0,
 '993342.10': 0,
 '9949197.1': 0,
 '9949197.2': 0,
 '9949197.3': 0,
 '9949197.4': 0,
 '9949197.5': 0,
 '9949197.6': 0,
 '9949197.7': 0,
 '9949209.2': 6,
 '9949209.3': 0,
 '9949209.4': 6,
 '9949209.5': 0,
 '9949209.6': 0,
 '9949209.11': 0,
 '9949209.12': 0,
 '9949209.15': 0,
 '9950360.1': 0,
 '9950360.2': 0,
 '9950360.3': 0,
 '9950360.4': 0,
 '9950360.5': 0,
 '9950360.6': 0,
 '9950360.7': 0,
 '9950360.8': 0,
 '9950360.9': 0,
 '9950360.10': 0,
 '9950360.11': 0,
 '9950360.12': 0,
 '9950360.13': 0,
 '9950360.14': 0,
 '9950360.15': 0,
 '9950360.16': 0,
 '9950360.17': 0,
 '9950360.18': 0,
 '9950360.19': 0,
 '9950360.20': 0,
 '9973276.1': 1,
 '9973276.2': 0,
 '9973276.3': 0,
 '9973276.4': 0,
 '9973276.5': 0,
 '9973276.6': 0,
 '9973276.7': 0,
 '9973276.8': 6,
 '9973276.9': 0,
 '9973276.10': 0,
 '9973276.11': 0,
 '9973276.12': 0,
 '9973276.13': 0,
 '9973276.14': 0,
 '9973276.15': 0,
 '9988281.1': 2,
 '9988281.2': 0,
 '9988281.3': 0,
 '9988281.4': 1,
 '9988281.5': 0,
 '9988281.6': 1,
 '9988281.7': 0,
 '9988281.8': 0,
 '9988281.9': 0,
 '9988281.10': 0,
 '9988281.11': 0}

In [24]:
# def get_candidates_name(candidates, ontology):
#     ''' 
#     Returns the name of the candidates
#     ------
#     candidates : list of list of CUIs : [[cui1], [cui2, cui3], ...]
#     ontology : BiomedicalOntology object
#     '''
#     candidates_name = {}
#     for candidate in candidates:
#         entity = ontology.entities.get(candidate)
#         candidates_name[entity.cui] = entity.name
#     return candidates_name



# def get_candidates_data(candidates, ontology):
#     ''' 
#     Returns the metadata of the candidates
#     ------
#     candidates : list of list of CUIs : [[cui1], [cui2, cui3], ...]
#     ontology : BiomedicalOntology object
#     '''
#     candidates_data = {}
#     for candidate in candidates:
#         entity = ontology.entities.get(candidate)
#         if entity:
#             entity_data = {
#                 'cui': entity.cui,
#                 'name': entity.name,
#                 'types': entity.types,
#                 'aliases': entity.aliases,
#                 'definition': entity.definition
#             }
#             candidates_data[entity.cui] = entity_data
#         else:
#             candidates_data[candidate] = {'error': f'Entity for {candidate} not found'}
#     return candidates_data

# res = get_candidates_data(candidates=mention2biencoder_candidates[mentions[0]], 
#                           ontology=ontology2)
# res
# len(res)
# # mention2biencoder_candidates[mentions[0]]

# # def get_candidates_data_v2(candidates) :  
# #     candidates_data = []
# #     for candidate in candidates:
# #         entity = candidate + " : " + cui2description[candidate]
# #         candidates_data.append(entity)
# #     return candidates_data

# # get_candidates_data_v2(mention2biencoder_candidates[mentions[0]])

In [25]:
# '''
# Create a string for gpt prompt with : 
# "Query : ... / Sentence (context+mention) : ... / Answer : cui
# etc...
# Query : ... / Sentence (context+mention) : ... / Answer : cui"
# '''
# def topk_examples(model,
#                   index,
#                   query, 
#                   corpus, 
#                   TrainMap_context2mention, 
#                   train_mention2text, 
#                   train_mention2gold, 
#                   ontology,
#                   k = 5) : 
#     ''' 
#     Given a query (context sentence), returns the top k most similar contexts from the corpus.
#     ------
#     query : str (context sentence)
#     corpus : list of str (all context sentences)
#     TrainMap_context2mention : dict (context sentence to mention_id)
#     train_mention2text : dict (mention_id to mention name)
#     ontology : BiomedicalOntology object
#     k : int (number of nearest neighbors)
#     '''
#     indices = knn_query(model, index, query, k)
#     result_list = []
#     for i, idx in enumerate(indices) :
#         NN_mention = corpus[idx]
#         # print("Nearest neighbor mention : ", NN_mention)
#         if NN_mention not in TrainMap_context2mention :
#             continue
#         mention_id = TrainMap_context2mention[NN_mention]
#         # print("mention_id :", mention_id)
#         mention_text = train_mention2text[mention_id]
#         cui = train_mention2gold[mention_id]
#         # print("cui :", cui)
#         gold = get_candidates_data(candidates=cui, ontology=ontology)
#         # print("gold :", gold)
#         result_list.append(f"Mention {i+1}: {mention_text} || Context: {NN_mention} || Correct CUI: {gold}")
    
#     res = "\n".join(result_list)
    
#     return res

In [26]:
system_instructions = """You are a professional data annotator and curator.
Your task is to identify the correct entity for a given mention based on the provided context and the descriptions of {number_candidates} candidate entities."""

system_instructions_recall = """You are a professional data annotator and curator.
Your task is to rank the candidate entities from best to worst for a given mention based on the provided context and the descriptions of each candidate entities."""

In [27]:
# def prompt_gpt(mention, 
#             context, 
#             candidates, 
#             system_instructions, 
#             topk_examples, 
#             llm = "gpt-4o-mini"): 
#     ''' 
#     mention : str (name of the mention to be linked)
#     context : str (context where the mention appears)
#     candidates : list of list of CUIs : [[cui1], [cui2, cui3], ...]
#     system_instructions : str (instructions for the LLM)
#     topk_examples : str (top k examples of similar contexts)
#     model : str (name of the model to use)
#     '''
#     completion = openai.chat.completions.create(
#         model = llm,
#         messages=[
#             {"role": "system", "content": system_instructions},
#             {
#                 "role": "user",
#                 "content": f""" 
#                 Here are a few examples : \n
#                 {topk_examples} \n

#                 This is the specific mention that needs to be linked to the correct entity : {mention} \n
                
#                 This is the context where the mention appears : {context} \n
                
#                 These are the candidate entities to choose from: {candidates} \n
#                 You must provide an answer among the candidates. \n
                
#                 Return the answer in the following format : CUI \n
                
#                 Do not add any explanations !
#                 """
#             },
#         ],
#         max_tokens= 2048,
#         temperature= 0,
#     )
#                 # Do not add any explanations ! 
#                 # Do not return anything except the correct CUI from the list of candidates.
#                 # If there are multiple possible entities, you can return multiple IDs.
                
#                 # Be careful not to mix it with another mention that could appear in the context !
                
#                 # This is the specific mention that needs to be linked to the correct entity : {mentions[i]}
#     return completion.choices[0].message.content

In [35]:
# def evaluate_gpt(mentions, 
#              mention2context, 
#              mention2biencoder_candidates, 
#              ontology, 
#              k, 
#              corpus,
#              TrainMap_context2mention,
#              train_mention2text,
#              train_mention2gold,
#              system_instructions,
#              index,
#              nlp_model,
#              llm = "gpt-4o-mini"):
#     ''' 
#     Run "prompt" function for each mention in the list of mentions.
#     Returns a dictionary {mention_id : predicted CUI}
#     -------
#     mentions : list (mention_ids)
#     ontology : BiomedicalOntology object
#     mention2context : dict (mention_id : context)
#     mention2biencoder_candidates : dict (mention_id : list of candidate CUIs)
#     k : int (number of nearest neighbors)
#     corpus : list of str (all context sentences)
#     TrainMap_context2mention : dict (context sentence to mention_id)
#     train_mention2text : dict (mention_id to mention name)
#     train_mention2gold : dict (mention_id to gold CUI)
#     system_instructions : str (instructions for the LLM)
#     index : faiss index
#     nlp_model : sentence-transformers model
#     llm : str (name of the model)
#     '''
#     results = {}
#     for i in range(len(mentions)) :
#         mention = mentions[i]
#         context = mention2context[mention]
#         candidates = get_candidates_data(candidates=mention2biencoder_candidates[mentions[i]], 
#                                          ontology=ontology)
#         # candidates = get_candidates_data_v2(mention2crossencoder_candidates[mention])
#         topk = topk_examples(model = nlp_model,
#                             index = index,
#                             query=context, 
#                             corpus=corpus, 
#                             TrainMap_context2mention=TrainMap_context2mention, 
#                             train_mention2text=train_mention2text, 
#                             train_mention2gold=train_mention2gold, 
#                             ontology=ontology, 
#                             k=k)

#         text = prompt_gpt(mention = mention, 
#                           context = context, 
#                           system_instructions=system_instructions,
#                           candidates = candidates, 
#                           topk_examples=topk, 
#                           llm = llm)
        
#         cand = extract_cui(text)
#         results[mention] = cand
        
#         if i%20 == 0:
#             print(f"i = {i}")

#     return results

In [36]:
# def scoring(results, mention2gold) :
#     ''' 
#     Return the score of of the model
#     -------
#     results : dictionary {mention_id : predicted CUI}
#     mention2gold : dictionary {mention_id : gold CUI}
#     '''
#     score = 0
#     for key, value in results.items():
#         if value in mention2gold[key] :
#             score += 1

#     return score/len(results)

In [51]:
# def error_analysis(results, ontology, mention2gold, mention2context) :
#     ''' 
#     Returns a dict of mention_id for mentions that were not correctly predicted
#     Each dict contains the gold cui, the predicted cui, the context of the mention.
#     -------
#     results : dictionary {mention_id : predicted CUI}
#     ontology : BiomedicalOntology object
#     mention2gold : dictionary {mention_id : gold CUI}
#     mention2context : dictionary {mention_id : context}
#     '''
#     error_mentions = defaultdict(dict)
#     for mention_id, predicted_cui in results.items() :
#         gold_cui = mention2gold[mention_id]
#         if predicted_cui not in gold_cui :
#             predicted_cui_metadata = get_candidates_data(candidates=[predicted_cui], 
#                                                          ontology=ontology)
#             gold_cui_metadata = get_candidates_data(candidates=[gold_cui[0]], 
#                                                     ontology=ontology)
#             mention_context = mention2context[mention_id]
#             error_mentions[mention_id] = {"query_context": mention_context, "gold_cui": gold_cui_metadata, "predicted_cui": predicted_cui_metadata}

#     return error_mentions

### Single prompt for error analysis

In [ ]:
# mention = '9931324.9' # "9973276.8"
mention = "9288106.17"
# i = 39
# mention = mentions[i]
text = mention2text[mention]
context = mention2context[mention]
candidates = get_candidates_data(candidates = mention2biencoder_candidates[mention], 
                                 ontology = ontology2)
topk = topk_examples(model = model,
                    index = index,
                    query=context, 
                    corpus=corpus, 
                    TrainMap_context2mention=TrainMap_context2mention, 
                    train_mention2text=train_mention2text, 
                    train_mention2gold=train_mention2gold, 
                    ontology=ontology2, 
                    k=3)
# random.shuffle(candidates)
# candidates = get_candidates_data_v2(mention2candidates[mentions[i]])

pred_cui = prompt_gpt(mention = text, 
                      context=context, 
                      candidates=candidates,
                      system_instructions=system_instructions, 
                      topk_examples=topk, 
                      llm = "gpt-4o-mini")
# model = "gpt-3.5-turbo-0125"
# model = "gpt-4o-2024-08-06"
print("Mention ID :", mention)
print("Context :", context)
print("Top k examples :", topk)
print("Text :", text)
print("Gold CUI :", mention2gold[mention])

print("Predicted CUI :", pred_cui)

In [ ]:
mention = "9288106.17"
# i = 39
# mention = mentions[i]
text = mention2text[mention]
context = mention2context[mention]
candidates = get_candidates_data(candidates = mention2biencoder_candidates[mention], 
                                 ontology = ontology2)
topk = topk_examples(model = model,
                    index = index,
                    query=context, 
                    corpus=corpus, 
                    TrainMap_context2mention=TrainMap_context2mention, 
                    train_mention2text=train_mention2text, 
                    train_mention2gold=train_mention2gold, 
                    ontology=ontology2, 
                    k=3)
print(f"""
You are a professional data annotator and curator.
Your task is to identify the correct entity for a given mention based on the provided context and the descriptions of 20 candidate entities.
      
Here are a few examples : \n
{topk} \n

This is the specific mention that needs to be linked to the correct entity : {text} \n

This is the context where the mention appears : {context} \n

These are the candidate entities to choose from: {candidates} \n
You must provide an answer among the candidates. \n

Return the answer in the following format : CUI \n
For instance : "MESH:D000000" "OMIM:000000" are valid answers. \n
Reason step by step but do not add provide any explanations to me ! I only want the final answer.
""")

In [ ]:
print("context :", context)
print("topk :", topk)

In [32]:
results = evaluate_gpt(llm = "gpt-4o-mini",
                    nlp_model=model,
                    index=index,
                    mentions=mentions[:5], 
                    mention2context=mention2context,
                    mention2biencoder_candidates=mention2biencoder_candidates,   
                    ontology=ontology2, 
                    k = 3, 
                    corpus=corpus,
                    TrainMap_context2mention=TrainMap_context2mention,
                    train_mention2text=train_mention2text,
                    train_mention2gold=train_mention2gold,
                    system_instructions=system_instructions)
results

Batches: 100%|██████████| 1/1 [00:00<00:00, 129.52it/s]

(1, 768)

i = 0

Batches: 100%|██████████| 1/1 [00:00<00:00, 92.59it/s]

(1, 768)

Batches: 100%|██████████| 1/1 [00:00<00:00, 63.42it/s]

(1, 768)

Batches: 100%|██████████| 1/1 [00:00<00:00, 68.30it/s]

(1, 768)

Batches: 100%|██████████| 1/1 [00:00<00:00, 127.94it/s]

(1, 768)

{'9288106.1': 'MESH:D001260',
 '9288106.2': 'MESH:D015458',
 '9288106.3': 'MESH:D001260',
 '9288106.4': 'MESH:D001260',
 '9288106.5': 'MESH:D030342'}

In [33]:
score = scoring(results=results, mention2gold=mention2gold)
score

1.0

In [31]:
### SAVE THE RESULTS ! IT'S EXPENSIVE TO RUN THE MODEL !!!

# with open("gpt4o_results.json", "w") as f:
#     json.dump(results, f, indent=4)

with open("gpt4o_results.json", "r") as f:
    results = json.load(f)

# results

In [35]:
error_mentions = error_analysis(results = results, 
                                ontology = ontology2, 
                                mention2gold = mention2gold, 
                                mention2context = mention2context)
error_mentions

defaultdict(dict, {})

# Evaluation with Mixtral

In [ ]:
from transformers import AutoModelForCausalLM, AutoTokenizer

mixtral_tokenizer = AutoTokenizer.from_pretrained("mistralai/Mistral-7B-Instruct-v0.3")
mixtral_model = AutoModelForCausalLM.from_pretrained("mistralai/Mistral-7B-Instruct-v0.3")

### ICL

In [44]:
def prompt_mistral(mention, context, candidates, topk_examples):
    ''' 
    Equivalent of the prompt function for the Mistral model.
    '''
    
    prompt_text = f"""
    You are a professional data annotator and curator.
    Your task is to identify the correct entity for a given mention based on the provided context and the descriptions of {number_candidates} candidate entities. \n
    
    Here are a few examples : \n
    {topk_examples} \n

    This is the specific mention that needs to be linked to the correct entity : {mention} \n
    
    This is the context where the mention appears : \n
    {context} \n
    
    These are the candidate entities to choose from: \n
    {candidates} \n
    
    You must provide an answer among the candidates. \n
    
    Return the answer in the following format : CUI
    Do not add any explanations!
    """

    # Tokenize input
    inputs = mixtral_tokenizer(prompt_text, return_tensors="pt", max_length=2048, truncation=True)

    # Generate output (you can adjust `max_new_tokens` to limit the output)
    with torch.no_grad():
        outputs = mixtral_model.generate(**inputs, max_new_tokens=300, temperature=0.0)

    # Decode the generated tokens
    generated_text = mixtral_tokenizer.decode(outputs[0], skip_special_tokens=True)

    # Extract the CUI answer (since the model generates the entire text, you might need to clean it)
    return generated_text.strip()

In [45]:
# mention = '9931324.9' # "9973276.8"
mention = "9888388.6"
# i = 39
# mention = mentions[i]
text = mention2text[mention]
context = mention2context[mention]
candidates = get_candidates_data(candidates=mention2biencoder_candidates[mention], 
                                 ontology=ontology2)
topk = topk_examples(query=context, 
                        corpus=corpus, 
                        TrainMap_context2mention=TrainMap_context2mention, 
                        train_mention2text=train_mention2text, 
                        train_mention2gold=train_mention2gold, 
                        ontology=ontology2, 
                        k=3)

pred_cui = prompt_mistral(text, context, candidates, topk_examples=topk)

print("Predicted CUI :", pred_cui)

Batches: 100%|██████████| 1/1 [00:00<00:00, 92.61it/s]
/nethome/cye73/conda_envs/bioel/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:492: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.

(1, 768)
Predicted CUI : You are a professional data annotator and curator.
    Your task is to identify the correct entity for a given mention based on the provided context and the descriptions of 64 candidate entities.


    Here are a few examples :

    Mention 1: peroxisomal disease || Context: Determination of 30 X-linked adrenoleukodystrophy mutations, including 15 not previously described. X-linked Adrenoleukodystrophy (X-ALD) is the most frequent [ENTITY_START] peroxisomal disease. [ENTITY_END] It mainly involves the nervous system white matter, adrenal cortex and testes. Several distinct clinical phenotypes are known. The principal biochemical abnormality is the accumulation of saturated very-long-chain fatty acids (VLCFAs || Correct CUI: {'MESH:D018901': {'cui': 'MESH:D018901', 'name': 'Peroxisomal Disorders', 'types': 'Disease', 'aliases': 'Acidemia, Hyperpipecolic|Acidemias, Hyperpipecolic|Adrenoleukodystrophies, Neonatal|Adrenoleukodystrophy, Autosomal Neonatal Form|Adrenoleukodystrophy, Autosomal, Neonatal Form|Adrenoleukodystrophy, Neonatal|Dysfunction, General Peroxisomal|Dysfunction, Multiple Peroxisomal|Dysfunctions, General Peroxisomal|Dysfunction, Single Peroxisomal|Dysfunctions, Multiple Peroxisomal|Dysfunctions, Single Peroxisomal|General Peroxisomal Dysfunction|General Peroxisomal Dysfunctions|Hyperpipecolatemia|Hyperpipecolic Acidemia|Hyperpipecolic Acidemias|Multiple Peroxisomal Dysfunction|Multiple Peroxisomal Dysfunctions|Neonatal Adrenoleukodystrophies|Neonatal Adrenoleukodystrophy|Peroxisomal Disorder|Peroxisomal Dysfunction, General|Peroxisomal Dysfunction, Multiple|Peroxisomal Dysfunctions, General|Peroxisomal Dysfunction, Single|Peroxisomal Dysfunctions, Multiple|Peroxisomal Dysfunctions, Single|Single Peroxisomal Dysfunction|Single Peroxisomal Dysfunctions', 'definition': 'A heterogeneous group of inherited metabolic disorders marked by absent or dysfunctional PEROXISOMES. Peroxisomal enzymatic abnormalities may be single or multiple. Biosynthetic peroxisomal pathways are compromised, including the ability to synthesize ether lipids and to oxidize long-chain fatty acid precursors. Diseases in this category include ZELLWEGER SYNDROME; INFANTILE REFSUM DISEASE; rhizomelic chondrodysplasia (CHONDRODYSPLASIA PUNCTATA, RHIZOMELIC); hyperpipecolic acidemia; neonatal adrenoleukodystrophy; and ADRENOLEUKODYSTROPHY (X-linked). Neurologic dysfunction is a prominent feature of most peroxisomal disorders.'}}
Mention 2: X-linked Adrenoleukodystrophy || Context: Determination of 30 X-linked adrenoleukodystrophy mutations, including 15 not previously described. X-linked Adrenoleukodystrophy [ENTITY_START] (X-ALD) [ENTITY_END] is the most frequent peroxisomal disease. It mainly involves the nervous system white matter, adrenal cortex and testes. Several distinct clinical phenotypes are known. The principal biochemical abnormality is the accumulation || Correct CUI: {'MESH:D000326': {'cui': 'MESH:D000326', 'name': 'Adrenoleukodystrophy', 'types': 'Disease', 'aliases': 'Addison Disease and Cerebral Sclerosis|Adrenoleukodystrophy, X-Linked|Adrenomyeloneuropathy|ALD|ALD (Adrenoleukodystrophy)|AMN, INCLUDED|Bronze Schilder Disease|Leukodystrophies, Melanodermic|Leukodystrophy, Melanodermic|Melanodermic Leukodystrophy|MELANODERMIC LEUKODYSTROPHY ADRENOMYELONEUROPATHY, INCLUDED|Schilder Addison Complex|Schilder-Addison Complex|Siemerling Creutzfeldt Disease|Siemerling-Creutzfeldt Disease|X ALD|X-ALD|X ALD (X Linked Adrenoleukodystrophy)|X-ALD (X-Linked Adrenoleukodystrophy)|X Linked Adrenoleukodystrophy|X-Linked Adrenoleukodystrophy', 'definition': 'An X-linked recessive disorder characterized by the accumulation of saturated very long chain fatty acids in the LYSOSOMES of ADRENAL CORTEX and the white matter of CENTRAL NERVOUS SYSTEM. This disease occurs almost exclusively in the males. Clinical features include the childhood onset of ATAXIA; NEUROBEHAVIORAL MANIFESTATIONS; HYPERPIGMENTATION; ADRENAL INSUFFICIENCY; SEIZURES; MUSCLE SPASTICITY; and DEMENTIA. The slowly progressive adult form is called adrenomyeloneuropathy. The defective gene ABCD1 is located at Xq28, and encodes the adrenoleukodystrophy protein (ATP-BINDING CASSETTE TRANSPORTERS).'}}


    This is the specific mention that needs to be linked to the correct entity : 9888388.6


    This is the context where the mention appears : coproporphyria (HC) is an acute hepatic porphyria with autosomal dominant inheritance caused by deficient activity of coproporphyrinogen III oxidase (CPO). Clinical manifestations of the disease are characterized by acute attacks of [ENTITY_START] neurological dysfunction [ENTITY_END] often precipitated by drugs, fasting, cyclical hormonal changes, or infectious diseases. Skin photosensitivity may also be present. The seven exons, the exon/intron boundaries and part of 3 noncoding sequence of the


    These are the candidate entities to choose from: {'MESH:D009461': {'cui': 'MESH:D009461', 'name': 'Neurologic Manifestations', 'types': 'Disease', 'aliases': 'Deficit, Focal Neurologic|Deficit, Neurologic|Deficits, Focal Neurologic|Deficits, Neurologic|Dysfunction, Neurologic|Dysfunctions, Neurologic|Finding, Neurologic|Findings, Neurologic|Focal Neurologic Deficit|Focal Neurologic Deficits|Manifestation, Neurologic|Manifestation, Neurological|Manifestations, Neurologic|Manifestations, Neurological|Neurological Manifestation|Neurological Manifestations|Neurologic Deficit|Neurologic Deficit, Focal|Neurologic Deficits|Neurologic Deficits, Focal|Neurologic Dysfunction|Neurologic Dysfunctions|Neurologic Finding|Neurologic Findings|Neurologic Manifestation|Neurologic Sign|Neurologic Signs|Neurologic Signs and Symptoms|Neurologic Symptom|Neurologic Symptoms|Sign, Neurologic|Signs, Neurologic|Symptom, Neurologic|Symptoms, Neurologic', 'definition': 'Clinical signs and symptoms caused by nervous system injury or dysfunction.'}, 'MESH:D009422': {'cui': 'MESH:D009422', 'name': 'Nervous System Diseases', 'types': 'Disease', 'aliases': 'Disease, Nervous System|Diseases, Nervous System|Diseases of the Nervous System|Diseases of the Nervous System, Central|Diseases of the Nervous System, Peripheral|Diseases of the Nervous System, Peripheral Nervous System|Diseases of the Nervous System, Peripheral Nervous System, Autonomic|Diseases of the Nervous System, Peripheral Nervous System, Autonomic Nervous System|Diseases of the Nervous System, Peripheral Nervous System, Autonomic Nervous System, Autonomic Ganglia|Diseases of the Nervous System, Peripheral Nervous System, Autonomic Nervous System, Autonomic Ganglia, Parasympathetic|Diseases of the Nervous System, Peripheral Nervous System, Autonomic Nervous System, Autonomic Ganglia, Sympathetic|Diseases of the Nervous System, Peripheral Nervous System, Autonomic Nervous System, Autonomic Ganglia, Sympathetic, Adrenergic|Diseases of the Nervous System, Peripheral Nervous System, Autonomic Nervous System, Autonomic Ganglia, Sympathetic, Cholinergic|D

# Flan T5 model

In [28]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

# Load Flan-T5 model and tokenizer
flan_tokenizer = AutoTokenizer.from_pretrained("google/flan-t5-xxl")
flan_model = AutoModelForSeq2SeqLM.from_pretrained("google/flan-t5-xxl")

/nethome/cye73/conda_envs/bioel/lib/python3.9/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
Loading checkpoint shards: 100%|██████████| 5/5 [00:02<00:00,  1.74it/s]

In [29]:
def prompt_flan_t5(mention, context, candidates, topk_examples):
    prompt_text = f"""
    You are a professional data annotator and curator.
    Your task is to identify the correct entity for a given mention based on the provided context and the descriptions of 64 candidate entities.

    Here are a few examples: \n
    {topk_examples} \n

    This is the specific mention that needs to be linked to the correct entity: {mention} \n

    This is the context where the mention appears : \n
    {context} \n
    
    These are the candidate entities to choose from: \n
    {candidates} \n
    
    You must provide an answer among the candidates. \n

    Return the answer in the following format: CUI
    Do not add any explanations!
    """

    inputs = flan_tokenizer(prompt_text, return_tensors="pt", max_length=2048, truncation=True)

    outputs = flan_model.generate(**inputs, max_new_tokens=100, temperature=0.0)
    generated_text = flan_tokenizer.decode(outputs[0], skip_special_tokens=True)
    return generated_text.strip()

In [ ]:
mention = "9988281.10"
text = mention2text[mention]
context = mention2context[mention]
candidates = get_candidates_data(mention2biencoder_candidates[mention], ontology2)
topk = topk_examples(query=context, 
                        corpus=corpus, 
                        TrainMap_context2mention=TrainMap_context2mention, 
                        train_mention2text=train_mention2text, 
                        train_mention2gold=train_mention2gold, 
                        ontology=ontology2, 
                        k=3)

pred_cui = prompt_flan_t5(mention = text, context = context, candidates=candidates, topk_examples=topk)

print("Mention ID :", mention)
print("Context :", context)
print("Top k examples :", topk)
print("Text :", mention2text[mention])
print("Gold CUI :", mention2gold[mention])
print("Predicted CUI :", pred_cui)

In [84]:
CUIs = [v[0] for k, v in mention2gold.items()] # List of all gold CUIs from the test set (reduced one = only with hit_index < nb_candidates)

cui2name = get_candidates_name(CUIs, ontology2)
name2cui = {v: k for k, v in cui2name.items()}

name2cui[pred_cui]

'MESH:D009422'

# vllm
# LLAMA
Llama-3.1-8B-UltraMedical (71%)

Bio-Medical-Llama-3-8B (41%)

Laim/Llama-3.1-MedPalm2-imitate-8B-Instruct (17%)

meta-llama/Meta-Llama-3.1-8B-Instruct (79%) (91% for k=10)

mistralai/Mistral-7B-Instruct-v0.3 (82%) (84% for k=10)

mistralai/Mistral-Nemo-Instruct-2407 (90%)

ISTA-DASLab/Mixtral-8x7B-Instruct-v0_1-AQLM-2Bit-1x16-hf

In [26]:
# llm = LLM(
#     model="meta-llama/Meta-Llama-3.1-8B-Instruct",
#     enforce_eager=True,
# )

os.environ["CUDA_VISIBLE_DEVICES"] = "0,1"
device_1 = torch.device("cuda:0")  # First GPU (GPU 0)
device_2 = torch.device("cuda:1")  # Second GPU (GPU 1)

llm = LLM(
model="Qwen/Qwen2.5-7B-Instruct",
tensor_parallel_size=1,
dtype = "half",
gpu_memory_utilization=0.85,
max_logprobs=1000,
device=device_1,
max_model_len = 30000)

tokenizer = llm.get_tokenizer()

WARNING 09-21 19:00:15 config.py:1651] Casting torch.bfloat16 to torch.float16.
WARNING 09-21 19:00:15 config.py:365] Async output processing is only supported for CUDA or TPU. Disabling it for other platforms.
INFO 09-21 19:00:15 llm_engine.py:213] Initializing an LLM engine (v0.6.0) with config: model='Qwen/Qwen2.5-7B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2.5-7B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=30000, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda:0, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=Qwen/Qwen2.5-7B-Instruct, use_v2_block_manager=False, num_scheduler_steps=1, enable_prefix_caching=False, use_async_output_proc=False)
INFO 09-21 19:00:16 selector.py:217] Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
INFO 09-21 19:00:16 selector.py:116] Using XFormers backend.

/nethome/cye73/conda_envs/bioel/lib/python3.9/site-packages/xformers/ops/fmha/flash.py:211: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_fwd")
/nethome/cye73/conda_envs/bioel/lib/python3.9/site-packages/xformers/ops/fmha/flash.py:344: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_bwd")

INFO 09-21 19:00:16 model_runner.py:915] Starting to load model Qwen/Qwen2.5-7B-Instruct...
INFO 09-21 19:00:16 selector.py:217] Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
INFO 09-21 19:00:16 selector.py:116] Using XFormers backend.
INFO 09-21 19:00:16 weight_utils.py:236] Using model weights format ['*.safetensors']

Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  25% Completed | 1/4 [00:01<00:04,  1.43s/it]
Loading safetensors checkpoint shards:  50% Completed | 2/4 [00:02<00:02,  1.42s/it]
Loading safetensors checkpoint shards:  75% Completed | 3/4 [00:04<00:01,  1.47s/it]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:05<00:00,  1.50s/it]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:05<00:00,  1.48s/it]

INFO 09-21 19:00:23 model_runner.py:926] Loading model weights took 14.2487 GB
INFO 09-21 19:00:29 gpu_executor.py:122] # GPU blocks: 22472, # CPU blocks: 4681
INFO 09-21 19:00:33 model_runner.py:1217] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
INFO 09-21 19:00:33 model_runner.py:1221] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
INFO 09-21 19:00:59 model_runner.py:1335] Graph capturing finished in 26 secs.

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

In [27]:
# llm2 = LLM(
# model="mistralai/Mistral-7B-Instruct-v0.3",
# tensor_parallel_size=1,
# dtype = "half",
# gpu_memory_utilization=0.9,
# max_logprobs=1000,
# device=device_2)

In [28]:
# torch.cuda.set_device(0)
# torch.cuda.empty_cache()

In [29]:

# def prompt_vllm(mention, 
#                 context, 
#                 system_instructions, 
#                 candidates, 
#                 topk_examples, 
#                 llm, 
#                 tokenizer, 
#                 sampling_params,
#                 reasoning=False):
#     ''' 
#     mention : str (name of the mention to be linked)
#     context : str (context where the mention appears)
#     system_instructions : str (instructions for the LLM)
#     candidates : list of list of CUIs : [[cui1], [cui2, cui3], ...]
#     topk_examples : str (top k examples of similar contexts)
#     llm : LLM model
#     tokenizer : AutoTokenizer
#     sampling_params : SamplingParams config
#     reasoning : bool (whether to use reasoning or not)
#     '''
#     prompt_text = f"""
#     Here are a few examples: \n
#     {topk_examples} \n

#     This is the specific mention that needs to be linked to the correct entity: {mention} \n

#     This is the context where the mention appears: \n
#     {context} \n
    
#     These are the candidate entities to choose from: \n
#     {candidates} \n
    
#     You MUST PROVIDE an ANSWER among the candidates. \n

#     Return the answer in the following format: CUI
#     For instance : "MESH:D000000" "OMIM:000000" are valid answers. \n
#     Reason step by step but do not add provide any explanations to me ! I only want the final answer.
#     """
#     # Do not add provide any explanations ! But you must give AN answer.

#     messages = [
#     {"role": "system", "content": system_instructions},
#     {"role": "user", "content": prompt_text},
#     ]
#     prompts = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)

#     # Decode the generated tokens into text
#     outputs = llm.generate(prompts=prompts, sampling_params=sampling_params)
#     answer = outputs[0].outputs[0].text

#     return answer

In [31]:
mention_id = "9448273.1"
mention_name = mention2text[mention_id]
context = mention2context[mention_id]
candidates = get_candidates_data(mention2biencoder_candidates[mention_id], ontology2)
topk = topk_examples(model = model, # sentence transformer model
                    index=index,
                    query=context,
                    corpus=corpus,
                    TrainMap_context2mention=TrainMap_context2mention,
                    train_mention2text=train_mention2text,
                    train_mention2gold=train_mention2gold,
                    ontology=ontology2,
                    k=3)

prompt = generate_prompt_text(mention = mention_name,
                              context=context,
                              candidates=candidates,
                              topk_examples=topk,
                              recall=False,
                              recall_k=5,
                              mention_id=mention_id)

# Generate the prediction using LLaMA 8B
pred_cui = prompt_vllm(prompt = prompt,
                       system_instructions=system_instructions,
                       llm=llm,
                       tokenizer=tokenizer,
                       sampling_params=sampling_params)
answer = extract_last_cui(pred_cui)

# Output the results
print("Mention ID:", mention_id)
print("Context:", context)
print("Top k examples:", topk)
print("Text:", mention2text[mention_id])
print("Gold CUI:", mention2gold[mention_id])
print("Predicted CUI:", pred_cui)
print("Final answer :", answer)

Batches: 100%|██████████| 1/1 [00:00<00:00, 113.81it/s]

(1, 768)

Processed prompts: 100%|██████████| 1/1 [00:05<00:00,  5.45s/it, est. speed input: 3876.33 toks/s, output: 1.83 toks/s]

Mention ID: 9448273.1
Context: The [ENTITY_START] von Hippel-Lindau tumor [ENTITY_END] suppressor gene is required for cell cycle exit upon serum withdrawal. The inactivation of the von Hippel-Lindau (VHL) tumor suppressor gene predisposes affected individuals to the human VHL cancer syndrome
Top k examples: Mention 1: von Hippel-Lindau || Context: Constitutional [ENTITY_START] von Hippel-Lindau [ENTITY_END] (VHL) gene deletions detected in VHL families by fluorescence in situ hybridization. von Hippel-Lindau (VHL) disease is an autosomal dominantly inherited cancer syndrome predisposing to a variety of tumor types that || Correct CUI: {'MESH:D006623': {'cui': 'MESH:D006623', 'name': 'von Hippel-Lindau Disease', 'types': 'Disease', 'aliases': "Angiomatoses, Familial Cerebelloretinal|Angiomatoses, Familial Cerebello-Retinal|Angiomatosis, Familial Cerebelloretinal|Angiomatosis, Familial Cerebello-Retinal|Angiomatosis Retinae|Cerebelloretinal Angiomatoses, Familial|Cerebello-Retinal Angiomatoses, Familial|Cerebelloretinal Angiomatosis, Familial|Cerebello-Retinal Angiomatosis, Familial|Familial Cerebelloretinal Angiomatoses|Familial Cerebello-Retinal Angiomatoses|Familial Cerebelloretinal Angiomatosis|Familial Cerebello Retinal Angiomatosis|Familial Cerebello-Retinal Angiomatosis|Hippel Lindau Disease|Hippel-Lindau Disease|Lindau Disease|Lindau's Disease|Lindaus Disease|Lindau's Diseases|VHLS|VHL Syndrome|VHL Syndromes|VHL VON HIPPEL-LINDAU SYNDROME, MODIFIERS OF, INCLUDED|von Hippel Lindau Disease|von Hippel Lindau Syndrome|von Hippel-Lindau Syndrome", 'definition': 'An autosomal dominant disorder caused by mutations in a tumor suppressor gene. This syndrome is characterized by abnormal growth of small blood vessels leading to a host of neoplasms. They include HEMANGIOBLASTOMA in the RETINA; CEREBELLUM; and SPINAL CORD; PHEOCHROMOCYTOMA; pancreatic tumors; and renal cell carcinoma (see CARCINOMA, RENAL CELL). Common clinical signs include HYPERTENSION and neurological dysfunctions.'}}
Mention 2: von Hippel-Lindau || Context: Constitutional von Hippel-Lindau [ENTITY_START] (VHL) [ENTITY_END] gene deletions detected in VHL families by fluorescence in situ hybridization. von Hippel-Lindau (VHL) disease is an autosomal dominantly inherited cancer syndrome predisposing to a variety of tumor types that include || Correct CUI: {'MESH:D006623': {'cui': 'MESH:D006623', 'name': 'von Hippel-Lindau Disease', 'types': 'Disease', 'aliases': "Angiomatoses, Familial Cerebelloretinal|Angiomatoses, Familial Cerebello-Retinal|Angiomatosis, Familial Cerebelloretinal|Angiomatosis, Familial Cerebello-Retinal|Angiomatosis Retinae|Cerebelloretinal Angiomatoses, Familial|Cerebello-Retinal Angiomatoses, Familial|Cerebelloretinal Angiomatosis, Familial|Cerebello-Retinal Angiomatosis, Familial|Familial Cerebelloretinal Angiomatoses|Familial Cerebello-Retinal Angiomatoses|Familial Cerebelloretinal Angiomatosis|Familial Cerebello Retinal Angiomatosis|Familial Cerebello-Retinal Angiomatosis|Hippel Lindau Disease|Hippel-Lindau Disease|Lindau Disease|Lindau's Disease|Lindaus Disease|Lindau's Diseases|VHLS|VHL Syndrome|VHL Syndromes|VHL VON HIPPEL-LINDAU SYNDROME, MODIFIERS OF, INCLUDED|von Hippel Lindau Disease|von Hippel Lindau Syndrome|von Hippel-Lindau Syndrome", 'definition': 'An autosomal dominant disorder caused by mutations in a tumor suppressor gene. This syndrome is characterized by abnormal growth of small blood vessels leading to a host of neoplasms. They include HEMANGIOBLASTOMA in the RETINA; CEREBELLUM; and SPINAL CORD; PHEOCHROMOCYTOMA; pancreatic tumors; and renal cell carcinoma (see CARCINOMA, RENAL CELL). Common clinical signs include HYPERTENSION and neurological dysfunctions.'}}
Mention 3: renal cell carcinoma || Context: Mutations of the VHL gene in sporadic renal cell carcinoma: definition of a risk factor for VHL patients to develop an [ENTITY_START] RCC. [ENTITY_END] To investigate the nature of somatic von Hippel-Lindau (VHL) mutations, we analyzed 173 primary sporadic human renal cell carcinomas for mutations of the VHL tumor suppressor gene, using polymerase chain reaction || Correct CUI: {'MESH:D002292': {'cui': 'MESH:D002292', 'name': 'Carcinoma, Renal Cell', 'types': 'Disease', 'aliases': 'Adenocarcinoma Of Kidney|ADENOCARCINOMA OF KIDNEY NONPAPILLARY RENAL CARCINOMA 1 LOCUS, INCLUDED|Adenocarcinoma Of Kidneys|Adenocarcinoma, Renal|Adenocarcinoma, Renal Cell|Adenocarcinomas, Renal Cell|Cancer, Renal Cell|Carcinoma, Collecting Duct|Carcinoma, Collecting Duct (Kidney)|Carcinoma, Hypernephroid|Carcinoma, Nephroid|Carcinoma, Renal|Carcinomas, Collecting Duct|Carcinomas, Collecting Duct (Kidney)|Carcinomas, Renal Cell|Chromophil Renal Cell Carcinoma|Chromophobe Renal Cell Carcinoma|Clear Cell Renal Carcinoma|Clear Cell Renal Cell Carcinoma|Collecting Duct Carcinoma|Collecting Duct Carcinoma (Kidney)|Collecting Duct Carcinoma of the Kidney|Collecting Duct Carcinomas|Collecting Duct Carcinomas (Kidney)|Grawitz Tumor|Hypernephroid Carcinoma|Hypernephroid Carcinomas|Hypernephroma|Hypernephromas|Kidney, Adenocarcinoma Of|Nephroid Carcinoma|Nephroid Carcinomas|NRC1, INCLUDED|Papillary Renal Cell Carcinoma|RCC|RCCP1|RCCX1|Renal Adenocarcinoma|Renal Adenocarcinomas|Renal Carcinoma|Renal Carcinomas|Renal Cell Adenocarcinoma|Renal Cell Adenocarcinomas|Renal Cell Cancer|Renal Cell Cancers|Renal Cell Carcinoma|RENAL CELL CARCINOMA, NONPAPILLARY|Renal Cell Carcinoma, Papillary|RENAL CELL CARCINOMA, PAPILLARY, 1|Renal Cell Carcinomas|RENAL CELL CARCINOMA, Xp11-ASSOCIATED|Renal Collecting Duct Carcinoma|Sarcomatoid Renal Cell Carcinoma|Tumor, Grawitz', 'definition': 'A heterogeneous group of sporadic or hereditary carcinoma derived from cells of the KIDNEYS. There are several subtypes including the clear cells, the papillary, the chromophobe, the collecting duct, the spindle cells (sarcomatoid), or mixed cell-type carcinoma.'}}
Text: von Hippel-Lindau tumor
Gold CUI: ['MESH:D006623']
Predicted CUI: MESH:D006623
Final answer : MESH:D006623

In [44]:
print(prompt)

        Here are a few examples:
Mention 1: von Hippel-Lindau || Context: Constitutional [ENTITY_START] von Hippel-Lindau [ENTITY_END] (VHL) gene deletions detected in VHL families by fluorescence in situ hybridization. von Hippel-Lindau (VHL) disease is an autosomal dominantly inherited cancer syndrome predisposing to a variety of tumor types that || Correct CUI: {'MESH:D006623': {'cui': 'MESH:D006623', 'name': 'von Hippel-Lindau Disease', 'types': 'Disease', 'aliases': "Angiomatoses, Familial Cerebelloretinal|Angiomatoses, Familial Cerebello-Retinal|Angiomatosis, Familial Cerebelloretinal|Angiomatosis, Familial Cerebello-Retinal|Angiomatosis Retinae|Cerebelloretinal Angiomatoses, Familial|Cerebello-Retinal Angiomatoses, Familial|Cerebelloretinal Angiomatosis, Familial|Cerebello-Retinal Angiomatosis, Familial|Familial Cerebelloretinal Angiomatoses|Familial Cerebello-Retinal Angiomatoses|Familial Cerebelloretinal Angiomatosis|Familial Cerebello Retinal Angiomatosis|Familial Cerebello-Retinal Angiomatosis|Hippel Lindau Disease|Hippel-Lindau Disease|Lindau Disease|Lindau's Disease|Lindaus Disease|Lindau's Diseases|VHLS|VHL Syndrome|VHL Syndromes|VHL VON HIPPEL-LINDAU SYNDROME, MODIFIERS OF, INCLUDED|von Hippel Lindau Disease|von Hippel Lindau Syndrome|von Hippel-Lindau Syndrome", 'definition': 'An autosomal dominant disorder caused by mutations in a tumor suppressor gene. This syndrome is characterized by abnormal growth of small blood vessels leading to a host of neoplasms. They include HEMANGIOBLASTOMA in the RETINA; CEREBELLUM; and SPINAL CORD; PHEOCHROMOCYTOMA; pancreatic tumors; and renal cell carcinoma (see CARCINOMA, RENAL CELL). Common clinical signs include HYPERTENSION and neurological dysfunctions.'}}
Mention 2: von Hippel-Lindau || Context: Constitutional von Hippel-Lindau [ENTITY_START] (VHL) [ENTITY_END] gene deletions detected in VHL families by fluorescence in situ hybridization. von Hippel-Lindau (VHL) disease is an autosomal dominantly inherited cancer syndrome predisposing to a variety of tumor types that include || Correct CUI: {'MESH:D006623': {'cui': 'MESH:D006623', 'name': 'von Hippel-Lindau Disease', 'types': 'Disease', 'aliases': "Angiomatoses, Familial Cerebelloretinal|Angiomatoses, Familial Cerebello-Retinal|Angiomatosis, Familial Cerebelloretinal|Angiomatosis, Familial Cerebello-Retinal|Angiomatosis Retinae|Cerebelloretinal Angiomatoses, Familial|Cerebello-Retinal Angiomatoses, Familial|Cerebelloretinal Angiomatosis, Familial|Cerebello-Retinal Angiomatosis, Familial|Familial Cerebelloretinal Angiomatoses|Familial Cerebello-Retinal Angiomatoses|Familial Cerebelloretinal Angiomatosis|Familial Cerebello Retinal Angiomatosis|Familial Cerebello-Retinal Angiomatosis|Hippel Lindau Disease|Hippel-Lindau Disease|Lindau Disease|Lindau's Disease|Lindaus Disease|Lindau's Diseases|VHLS|VHL Syndrome|VHL Syndromes|VHL VON HIPPEL-LINDAU SYNDROME, MODIFIERS OF, INCLUDED|von Hippel Lindau Disease|von Hippel Lindau Syndrome|von Hippel-Lindau Syndrome", 'definition': 'An autosomal dominant disorder caused by mutations in a tumor suppressor gene. This syndrome is characterized by abnormal growth of small blood vessels leading to a host of neoplasms. They include HEMANGIOBLASTOMA in the RETINA; CEREBELLUM; and SPINAL CORD; PHEOCHROMOCYTOMA; pancreatic tumors; and renal cell carcinoma (see CARCINOMA, RENAL CELL). Common clinical signs include HYPERTENSION and neurological dysfunctions.'}}
Mention 3: renal cell carcinoma || Context: Mutations of the VHL gene in sporadic renal cell carcinoma: definition of a risk factor for VHL patients to develop an [ENTITY_START] RCC. [ENTITY_END] To investigate the nature of somatic von Hippel-Lindau (VHL) mutations, we analyzed 173 primary sporadic human renal cell carcinomas for mutations of the VHL tumor suppressor gene, using polymerase chain reaction || Correct CUI: {'MESH:D002292': {'cui': 'MESH:D002292', 'name': 'Carcinoma, Renal Cell', 'types': 'Disease', 'aliases': 'Adenocarcinoma Of Kidney|ADENOCARCINOMA OF KIDNEY NONPAPILLARY RENAL CARCINOMA 1 LOCUS, INCLUDED|Adenocarcinoma Of Kidneys|Adenocarcinoma, Renal|Adenocarcinoma, Renal Cell|Adenocarcinomas, Renal Cell|Cancer, Renal Cell|Carcinoma, Collecting Duct|Carcinoma, Collecting Duct (Kidney)|Carcinoma, Hypernephroid|Carcinoma, Nephroid|Carcinoma, Renal|Carcinomas, Collecting Duct|Carcinomas, Collecting Duct (Kidney)|Carcinomas, Renal Cell|Chromophil Renal Cell Carcinoma|Chromophobe Renal Cell Carcinoma|Clear Cell Renal Carcinoma|Clear Cell Renal Cell Carcinoma|Collecting Duct Carcinoma|Collecting Duct Carcinoma (Kidney)|Collecting Duct Carcinoma of the Kidney|Collecting Duct Carcinomas|Collecting Duct Carcinomas (Kidney)|Grawitz Tumor|Hypernephroid Carcinoma|Hypernephroid Carcinomas|Hypernephroma|Hypernephromas|Kidney, Adenocarcinoma Of|Nephroid Carcinoma|Nephroid Carcinomas|NRC1, INCLUDED|Papillary Renal Cell Carcinoma|RCC|RCCP1|RCCX1|Renal Adenocarcinoma|Renal Adenocarcinomas|Renal Carcinoma|Renal Carcinomas|Renal Cell Adenocarcinoma|Renal Cell Adenocarcinomas|Renal Cell Cancer|Renal Cell Cancers|Renal Cell Carcinoma|RENAL CELL CARCINOMA, NONPAPILLARY|Renal Cell Carcinoma, Papillary|RENAL CELL CARCINOMA, PAPILLARY, 1|Renal Cell Carcinomas|RENAL CELL CARCINOMA, Xp11-ASSOCIATED|Renal Collecting Duct Carcinoma|Sarcomatoid Renal Cell Carcinoma|Tumor, Grawitz', 'definition': 'A heterogeneous group of sporadic or hereditary carcinoma derived from cells of the KIDNEYS. There are several subtypes including the clear cells, the papillary, the chromophobe, the collecting duct, the spindle cells (sarcomatoid), or mixed cell-type carcinoma.'}}

        This is the specific mention that needs to be linked to the correct entity: von Hippel-Lindau tumor

        This is the context where the mention appears:
The [ENTITY_START] von Hippel-Lindau tumor [ENTITY_END] suppressor gene is required for cell cycle exit upon serum withdrawal. The inactivation of the von Hippel-Lindau (VHL) tumor suppressor gene predisposes affected individuals to the human VHL cancer syndrome

        These are the candidate entities to choose from:

In [36]:
# def evaluate_vllm(
#     llm,
#     nlp_model,
#     tokenizer,
#     index,
#     system_instructions,
#     mentions,
#     ontology,
#     corpus,
#     mention2context,
#     mention2biencoder_candidates,
#     mention2text,
#     TrainMap_context2mention,
#     train_mention2text,
#     train_mention2gold,
#     k,
#     sampling_params,
#     reasoning = False,
# ):
#     """
#     Run "prompt" function for each mention in the list of mentions.
#     Returns a dictionary {mention_id : predicted CUI}
#     -------
#     llm : LLM model
#     nlp_model : SentenceTransformer model
#     tokenizer : AutoTokenizer
#     index : faiss index
#     system_instructions : str (instructions for the LLM)
#     mentions : list (mention_ids)
#     ontology : BiomedicalOntology object
#     corpus : list of str (all context sentences)
#     mention2context : dict (mention_id : context)
#     mention2biencoder_candidates : dict (mention_id : list of candidate CUIs)
#     mention2text : dict (mention_id : mention name)
#     TrainMap_context2mention : dict (context sentence to mention_id)
#     train_mention2text : dict (mention_id to mention name)
#     train_mention2gold : dict (mention_id to gold CUI)
#     k : int (number of nearest neighbors)
#     sampling_params : SamplingParams config
#     reasoning : bool (whether to use reasoning or not)
#     """
#     results = {}
#     for i in range(len(mentions)):
#         mention_id = mentions[i]
#         mention_name = mention2text[mention_id]
#         context = mention2context[mention_id]
#         candidates = get_candidates_data(
#             mention2biencoder_candidates[mentions[i]], ontology
#         )
#         # candidates = get_candidates_data_v2(mention2crossencoder_candidates[mention])
#         topk = topk_examples(
#             model=nlp_model,  # sentence transformer model
#             index=index,
#             query=context,
#             corpus=corpus,
#             TrainMap_context2mention=TrainMap_context2mention,
#             train_mention2text=train_mention2text,
#             train_mention2gold=train_mention2gold,
#             ontology=ontology,
#             k=k,
#         )

#         text = prompt_vllm(
#             mention=mention_name,
#             context=context,
#             system_instructions=system_instructions,
#             candidates=candidates,
#             topk_examples=topk,
#             llm=llm,
#             tokenizer=tokenizer,
#             sampling_params=sampling_params,
#             reasoning = reasoning,
#         )
#         print("mention ID :", mention_id, "|| LLM answer :", text)
#         cand = extract_cui(text)
#         results[mention_id] = cand
#         if i % 20 == 0:
#             print(f"i = {i}")

#     return results

In [ ]:
results = evaluate_vllm(llm=llm,
                        nlp_model=model,
                        tokenizer=tokenizer,
                        index=index,
                        system_instructions=system_instructions,
                        mentions=mentions,
                        ontology=ontology2,
                        corpus=corpus,
                        mention2context=mention2context,
                        mention2biencoder_candidates=mention2biencoder_candidates,
                        mention2text=mention2text,
                        TrainMap_context2mention=TrainMap_context2mention,
                        train_mention2text=train_mention2text,
                        train_mention2gold=train_mention2gold,
                        k=3,
                        sampling_params=sampling_params)
results

In [45]:
score = scoring(results=results, 
                mention2gold=mention2gold)
score

1.0

## Result : With reasoning

In [28]:
### SAVE THE RESULTS (It's long to run the model 26mins)
    
# with open("Meta-Llama-3.1-8B-Instruct_k=10_reasoning_results.json", "w") as f:
#     json.dump(results, f, indent=4)

with open("data/biencoder/reasoning2/Meta-Llama-3.1-8B-Instruct_k=3_reasoning_results.json", "r") as f:
    results1r = json.load(f)
    
with open("data/biencoder/reasoning2/Meta-Llama-3.1-8B-Instruct_k=5_reasoning_results.json", "r") as f:
    results2r = json.load(f)
    
with open("data/biencoder/reasoning2/Meta-Llama-3.1-8B-Instruct_k=10_reasoning_results.json", "r") as f:
    results3r = json.load(f)
    
    
###############################################################  
with open("data/biencoder/reasoning2/Mistral-7B-Instruct-v0.3_k=3_reasoning_results.json", "r") as f:
    results4r = json.load(f)

with open("data/biencoder/reasoning2/Mistral-7B-Instruct-v0.3_k=5_reasoning_results.json", "r") as f:
    results5r = json.load(f)
    
with open("data/biencoder/reasoning2/Mistral-7B-Instruct-v0.3_k=10_reasoning_results.json", "r") as f:
    results6r = json.load(f)


###############################################################
with open("data/biencoder/reasoning2/Mistral-Nemo-Instruct-2407_k=3_reasoning_results.json", "r") as f:
    results7r = json.load(f)

with open("data/biencoder/reasoning2/Mistral-Nemo-Instruct-2407_k=5_reasoning_results.json", "r") as f:
    results8r = json.load(f)

with open("data/biencoder/reasoning2/Mistral-Nemo-Instruct-2407_k=10_reasoning_results.json", "r") as f:
    results9r = json.load(f)
    
    
###############################################################
with open("data/biencoder/reasoning2/Qwen2.5-7B-Instruct_k=3_reasoning_results.json", "r") as f:
    results10r = json.load(f)

# with open("data/biencoder/reasoning2/Qwen2.5-7B-Instruct_k=5_reasoning_results.json", "r") as f:
#     results11r = json.load(f)

# with open("data/biencoder/reasoning2/Qwen2.5-7B-Instruct_k=10_reasoning_results.json", "r") as f:
#     results12r = json.load(f)
    
    
###############################################################
with open("data/biencoder/reasoning2/Qwen2.5-14B-Instruct_k=3_reasoning_results.json", "r") as f:
    results13r = json.load(f)

# with open("data/biencoder/reasoning2/Qwen2.5-14B-Instruct_k=5_reasoning_results.json", "r") as f:
#     results14r = json.load(f)

# with open("data/biencoder/reasoning2/Qwen2.5-14B-Instruct_k=10_reasoning_results.json", "r") as f:
#     results15r = json.load(f)

In [29]:
# for mention_id in results.copy() :
#     if results[mention_id] is None:
#         del results[mention_id]

score1r = scoring(results = results1r, mention2gold = mention2gold)
print("Meta-Llama-3.1-8B-Instruct_k=3_reasoning_results :", score1r)
score2r = scoring(results = results2r, mention2gold = mention2gold)
print("Meta-Llama-3.1-8B-Instruct_k=5_reasoning_results:", score2r)
score3r = scoring(results = results3r, mention2gold = mention2gold)
print("Meta-Llama-3.1-8B-Instruct_k=10_reasoning_results:", score3r)

print("---------------------------------")

score4r = scoring(results = results4r, mention2gold = mention2gold)
print("Mistral-7B-Instruct-v0.3_k=3_reasoning_results :", score4r)
score5r = scoring(results = results5r, mention2gold = mention2gold)
print("Mistral-7B-Instruct-v0.3_k=5_reasoning_results :", score5r)
score6r = scoring(results = results6r, mention2gold = mention2gold)
print("Mistral-7B-Instruct-v0.3_k=10_reasoning_results :", score6r)

print("---------------------------------")

score7r = scoring(results = results7r, mention2gold = mention2gold)
print("Mistral-Nemo-Instruct-2407_k=3_reasoning_results :", score7r)
score8r = scoring(results = results8r, mention2gold = mention2gold)
print("Mistral-Nemo-Instruct-2407_k=5_reasoning_results:", score8r)
score9r = scoring(results = results9r, mention2gold = mention2gold)
print("Mistral-Nemo-Instruct-2407_k=10_reasoning_results:", score9r)

print("---------------------------------")

score10r = scoring(results = results10r, mention2gold = mention2gold)
print("Qwen2.5-7B-Instruct_k=3_results :", score10r)
# score11r = scoring(results = results11r, mention2gold = mention2gold)
# print("Qwen2.5-7B-Instruct_k=5_results:", score11r)
# score12r = scoring(results = results12r, mention2gold = mention2gold)
# print("Qwen2.5-7B-Instruct_k=10_results:", score12r)

print("---------------------------------")

score13r = scoring(results = results13r, mention2gold = mention2gold)
print("Qwen2.5-14B-Instruct_k=3_results :", score13r)
# score14r = scoring(results = results14r, mention2gold = mention2gold)
# print("Qwen2.5-14B-Instruct_k=5_results:", score14r)
# score15r = scoring(results = results15r, mention2gold = mention2gold)
# print("Qwen2.5-14B-Instruct_k=10_results:", score15r)

Meta-Llama-3.1-8B-Instruct_k=3_reasoning_results : 0.87875
Meta-Llama-3.1-8B-Instruct_k=5_reasoning_results: 0.87375
Meta-Llama-3.1-8B-Instruct_k=10_reasoning_results: 0.85125
---------------------------------
Mistral-7B-Instruct-v0.3_k=3_reasoning_results : 0.85375
Mistral-7B-Instruct-v0.3_k=5_reasoning_results : 0.8675
Mistral-7B-Instruct-v0.3_k=10_reasoning_results : 0.87125
---------------------------------
Mistral-Nemo-Instruct-2407_k=3_reasoning_results : 0.795
Mistral-Nemo-Instruct-2407_k=5_reasoning_results: 0.81125
Mistral-Nemo-Instruct-2407_k=10_reasoning_results: 0.83625
---------------------------------
Qwen2.5-7B-Instruct_k=3_results : 0.8975
---------------------------------
Qwen2.5-14B-Instruct_k=3_results : 0.88375

In [30]:
error_mentions = error_analysis(results = results13r, 
                                ontology = ontology2, 
                                mention2gold = mention2gold, 
                                mention2context = mention2context)
error_mentions

defaultdict(dict,
            {'9288106.5': {'query_context': 'Clustering of missense mutations in the ataxia-telangiectasia gene in a sporadic T-cell leukaemia. Ataxia-telangiectasia (A-T) is a [ENTITY_START] recessive multi-system disorder [ENTITY_END] caused by mutations in the ATM gene at 11q22-q23 (ref. 3). The risk of cancer, especially lymphoid neoplasias, is substantially elevated in A-T patients and has long been associated with',
              'gold_cui': {'MESH:D030342': {'cui': 'MESH:D030342',
                'name': 'Genetic Diseases, Inborn',
                'types': 'Disease',
                'aliases': 'Defect, Single-Gene|Defects, Single-Gene|Disease, Genetic|Disease, Hereditary|Disease, Inborn Genetic|Diseases, Genetic|Diseases, Hereditary|Diseases, Inborn Genetic|Disorder, Genetic|Disorders, Genetic|Genetic Disease|Genetic Disease, Inborn|Genetic Diseases|Genetic Disorder|Genetic Disorders|Hereditary Disease|Hereditary Diseases|Inborn Genetic Disease|Inborn Genetic Diseases|Single-Gene Defect|Single Gene Defects|Single-Gene Defects',
                'definition': "Diseases that are caused by genetic mutations present during embryo or fetal development, although they may be observed later in life. The mutations may be inherited from a parent's genome or they may be acquired in utero."}},
              'predicted_cui': {'MESH:D009358': {'cui': 'MESH:D009358',
                'name': 'Congenital, Hereditary, and Neonatal Diseases and Abnormalities',
                'types': 'Disease',
                'aliases': 'Congenital Disorder|Congenital Disorders|Disorder, Congenital|Disorders, Congenital|Neonatal Diseases and Abnormalities',
                'definition': 'Diseases existing at birth and often before birth, or that develop during the first month of life (INFANT, NEWBORN, DISEASES), regardless of causation. Of these diseases, those characterized by structural deformities are termed CONGENITAL ABNORMALITIES.'}}},
             '9288106.7': {'query_context': 'the ataxia-telangiectasia gene in a sporadic T-cell leukaemia. Ataxia-telangiectasia (A-T) is a recessive multi-system disorder caused by mutations in the ATM gene at 11q22-q23 (ref. 3). The risk of cancer, especially [ENTITY_START] lymphoid neoplasias, [ENTITY_END] is substantially elevated in A-T patients and has long been associated with chromosomal instability. By analysing tumour DNA from patients with sporadic T-cell prolymphocytic leukaemia (T-PLL), a rare clonal malignancy with',
              'gold_cui': {'MESH:D008223': {'cui': 'MESH:D008223',
                'name': 'Lymphoma',
                'types': 'Disease',
                'aliases': 'Germinoblastic Sarcoma|Germinoblastic Sarcomas|Germinoblastoma|Germinoblastomas|Lymphoma, Malignant|Lymphomas|Lymphomas, Malignant|Malignant Lymphoma|Malignant Lymphomas|Reticulolymphosarcoma|Reticulolymphosarcomas|Sarcoma, Germinoblastic|Sarcomas, Germinoblastic',
                'definition': 'A general term for various neoplastic diseases of the lymphoid tissue.'}},
              'predicted_cui': {'MESH:D009369': {'cui': 'MESH:D009369',
                'name': 'Neoplasms',
                'types': 'Disease',
                'aliases': 'Benign Neoplasm|Benign Neoplasms|Cancer|Cancers|Malignancies|Malignancy|Malignant Neoplasm|Malignant Neoplasms|Neoplasia|Neoplasias|Neoplasm|Neoplasm, Benign|Neoplasm, Malignant|Neoplasms, Benign|Neoplasms, Malignant|Tumor|Tumors',
                'definition': 'New abnormal growth of tissue. Malignant neoplasms show a greater degree of anaplasia and have the properties of invasion and metastasis, compared to benign neoplasms.'}}},
             '9288106.17': {'query_context': 'leukaemia seen in A-T, we demonstrate a high frequency of ATM mutations in T-PLL. In marked contrast to the ATM mutation pattern in A-T, the most frequent nucleotide changes in this [ENTITY_START] leukaemia [ENTITY_END] were missense mutations. These clustered in the region corresponding to the kinase domain, which is highly conserved in ATM-related proteins in mouse, yeast and Drosophila. The resulting amino-acid substitutions are predicted',
              'gold_cui': {'MESH:D007938': {'cui': 'MESH:D007938',
                'name': 'Leukemia',
                'types': 'Disease',
                'aliases': 'Leucocythaemia|Leucocythaemias|Leucocythemia|Leucocythemias|Leukemias',
                'definition': 'A progressive, malignant disease of the blood-forming organs, characterized by distorted proliferation and development of leukocytes and their precursors in the blood and bone marrow. Leukemias were originally termed acute or chronic based on life expectancy but now are classified according to cellular maturity. Acute leukemias consist of predominately immature cells; chronic leukemias are composed of more mature cells. (From The Merck Manual, 2006)'}},
              'predicted_cui': {'MESH:D015461': {'cui': 'MESH:D015461',
                'name': 'Leukemia, Prolymphocytic, T-Cell',
                'types': 'Disease',
                'aliases': 'Leukemia, Lymphocytic, Chronic, T Cell|Leukemia, Lymphocytic, Chronic, T-Cell|Leukemias, T-Cell Prolymphocytic|Leukemia, T Cell, Chronic|Leukemia, T-Cell, Chronic|Leukemia, T-Cell Prolymphocytic|Lymphocytic Leukemia, T Cell, Chronic|Lymphocytic Leukemia, T-Cell, Chronic|Prolymphocytic Leukemias, T-Cell|Prolymphocytic Leukemia, T-Cell|T-Cell Leukemia, Chronic|T Cell Prolymphocytic Leukemia|T-Cell Prolymphocytic Leukemia|T-Cell Prolymphocytic Leukemias|T-Lymphocytic Leukemia, Chronic',
                'definition': 'A lymphoid leukemia characterized by a profound LYMPHOCYTOSIS with or without LYMPHADENOPATHY, hepatosplenomegaly, frequently rapid progression, and short survival. It was formerly called T-cell chronic lymphocytic leukemia.'}}},
             '9288106.25': {'query_context': 'that this tumour suppressor is not frequently altered in this leukaemia. Occasional missense mutations in ATM were also found in tumour DNA from patients with B-cell non-Hodgkins lymphomas (B-NHL) and a [ENTITY_START] B-NHL [ENTITY_END] cell line. The evidence of a significant proportion of loss-of-function mutations and a complete absence of the normal copy of ATM in the majority of mutated tumours establishes somatic inactivation of',
              'gold_cui': {'MESH:D016393': {'cui': 'MESH:D016393',
                'name': 'Lymphoma, B-Cell',
                'types': 'Disease',
                'aliases': 'B Cell Lymphoma|B-Cell Lymphoma|B-Cell Lymphomas|Lymphoma, B Cell|Lymphomas, B-Cell',
                'definition': 'A group of heterogeneous lymphoid tumors generally expressing one or more B-cell antigens or representing malignant transformations of B-lymphocytes.'}},
              'predicted_cui': {'MESH:D008228': {'cui': 'MESH:D008228',
                'name': 'Lymphoma, Non-Hodgkin',
                'types': 'Disease',
                'aliases': "Diffuse Lymphoma|Diffuse Lymphomas|Diffuse Mixed Cell Lymphoma|Diffuse Mixed-Cell Lymphoma|Diffuse Mixed-Cell Lymphomas|Diffuse Mixed Small and Large Cell Lymphoma|Diffuse Small Cleaved Cell Lymphoma|Diffuse Small Cleaved-Cell Lymphoma|Diffuse Undifferentiated Lymphoma|Diffuse Undifferentiated Lymphomas|High-Grade Lymphoma|High-Grade Lymphomas|Intermediate-Grade Lymphoma|Intermediate-Grade Lymphomas|Low-Grade Lymphoma|Low-Grade Lymphomas|Lymphatic Sarcoma|Lymphatic Sarcomas|Lymphocytic-Histiocytic Lymphoma, Mixed|Lymphocytic-Histiocytic Lymphomas, Mixed|Lymphoma, Atypical Diffuse Small Lymphoid|Lymphoma, Diffuse|Lymphoma, Diffuse Mixed-Cell|Lymphoma, Diffuse, Mixed Lymphocytic-Histiocytic|Lymphoma, Diffuse Undifferentiated|Lymphoma, High Grade|Lymphoma, High-Grade|Lymphoma, Intermediate Grade|Lymphoma, Intermediate-Grade|Lymphoma, Low Grade|Lymphoma, Low-Grade|Lymphoma, Mixed|Lymphoma, Mixed Cell|Lymphoma, Mixed-Cell|Lymphoma, Mixed Cell, Diffuse|Lymphoma, Mixed-Cell, Diffuse|Lymphoma, Mixed Lymphocytic Histiocytic|Lymphoma, Mixed Lymphocytic-Histiocytic|Lymphoma, Mixed Small and Large Cell, Diffuse|Lymphoma, Nonhodgkin|Lymphoma, Non Hodgkin|Lymphoma, Non-Hodgkin, Familial|Lymphoma, Nonhodgkins|Lymphoma, Nonhodgkin's|Lymphoma, Non Hodgkins|Lymphoma, Non Hodgkin's|Lymphoma, Non-Hodgkins|Lymphoma, Non-Hodgkin's|Lymphoma, Pleomorphic|Lymphoma, Small and Large Cleaved-Cell, Diffuse|Lymphoma, Small Cleaved Cell, Diffuse|Lymphoma, Small Cleaved-Cell, Diffuse|Lymphoma, Small Noncleaved Cell|Lymphoma, Small Noncleaved-Cell|Lymphoma, Small Non Cleaved Cell|Lymphoma, Small Non-Cleaved-Cell|Lymphoma, Undifferentiated|Lymphoma, Undifferentiated, Diffuse|Lymphosarcoma|Lymphosarcomas|Mixed Cell Lymphoma|Mixed-Cell Lymphoma|Mixed Cell Lymphoma, Diffuse|Mixed-Cell Lymphoma, Diffuse|Mixed-Cell Lymphomas|Mixed Lymphocytic-Histiocytic Lymphoma|Mixed Lymphocytic-Histiocytic Lymphomas|Mixed Lymphoma|Mixed Lymphomas|Mixed Small and Large Cell Lymphoma, Diffuse|NHL|Noncleaved-Cell Lymphoma, Small|Non-Cleaved-Cell Lymphoma, Small|Non Hodgkin Lymphoma|Non-Hodgkin Lymphoma|Nonhodgkin's Lymphoma|Nonhodgkins Lymphoma|Non Hodgkin's Lymphoma|Non-Hodgkin's Lymphoma|Non-Hodgkins Lymphoma|Pleomorphic Lymphoma|Pleomorphic Lymphomas|Reticulosarcoma|Reticulosarcomas|Reticulum Cell Sarcoma|Reticulum-Cell Sarcoma|Reticulum Cell Sarcomas|Reticulum-Cell Sarcomas|Sarcoma, Lymphatic|Sarcoma, Reticulum Cell|Sarcoma, Reticulum-Cell|Small Cleaved Cell Lymphoma, Diffuse|Small Cleaved-Cell Lymphoma, Diffuse|Small Noncleaved Cell Lymphoma|Small Noncleaved-Cell Lymphoma|Small Non Cleaved Cell Lymphoma|Small Non-Cleaved-Cell Lymphoma|Small Noncleaved-Cell Lymphomas|Small Non-Cleaved-Cell Lymphomas|Undifferentiated Lymphoma|Undifferentiated Lymphoma, Diffuse|Undifferentiated Lymphomas",
                'definition': "Any of a group of malignant tumors of lymphoid tissue that differ from HODGKIN DISEASE, being more heterogeneous with respect to malignant cell lineage, clinical course, prognosis, and therapy. The only common feature among these tumors is the absence of giant REED-STERNBERG CELLS, a characteristic of Hodgkin's disease."}}},
             '932197.9': {'query_context': 'a factor (or factors) interfering at some step in the hemolytic assay of C5, rather than a true C5 inhibitor or inactivator. Of clinical interest are (a) the documentation of membranous [ENTITY_START] glomerulonephritis, [ENTITY_END] vasculitis, and arthritis in an individual lacking C5 (and its biologic functions), and (b) a remarkable propensity to bacterial infections in the proband, even during periods of low-dose or alternate-day corticosteroid',
              'gold_cui': {'MESH:D005921': {'cui': 'MESH:D005921',
                'name': 'Glomerulonephritis',
                'types': 'Disease',
                'aliases': 'Bright Disease|Glomerulonephritides|Kidney Scarring|Scarring, Kidney',
                'definition': 'Inflammation of the renal glomeruli (KIDNEY GLOMERULUS) that can be classified by the type of glomerular injuries including antibody deposition, complement activation, cellular proliferation, and glomerulosclerosis. These structural and functional abnormalities usually lead to HEMATURIA; PROTEINURIA; HYPERTENSION; and RENAL INSUFFICIENCY.'}},
              'predicted_cui': {'MESH:D015433': {'cui': 'MESH:D015433',
                'name': 'Glomerulonephritis, Membranous',
                'types': 'Disease',
                'aliases': 'Extramembranous Glomerulopathy|Glomerulonephritides, Idiopathic Membranous|Glomerulonephritides, Membranous|Glomerulonephritis, Idiopathic Membranous|Glomerulonephropathy, Membranous|Glomerulopathy, Extramembranous|Glomerulopathy, Membranous|Heymann Nephritis|Idiopathic Membranous Glomerulonephritides|Idiopathic Membranous Glomerulonephritis|Idiopathic Membranous Nephropathy|MBNP|Membranous Glomerulonephritides|Membranous Glomerulonephritides, Idiopathic|Membranous Glomerulonephritis|Membranous Glomerulonephritis, Idiopathic|Membranous Glomerulonephropathy|Membranous Glomerulopathy|Membranous Nephropathy|Membranous Nephropathy, Idiopathic|MEMBRANOUS NEPHROPATHY, SUSCEPTIBILITY TO|Nephritis, Heymann|Nephropathy, Idiopathic Membranous|Nephropathy, Membranous',
                'definition': 'A type of glomerulonephritis that is characterized by the accumulation of immune deposits (COMPLEMENT MEMBRANE ATTACK COMPLEX) on the outer aspect of the GLOMERULAR BASEMENT MEMBRANE. It progresses from subepithelial dense deposits, to basement membrane reaction and eventual thickening of the basement membrane.'}}},
             '932197.10': {'query_context': 'factor (or factors) interfering at some step in the hemolytic assay of C5, rather than a true C5 inhibitor or inactivator. Of clinical interest are (a) the documentation of membranous glomerulonephritis, [ENTITY_START] vasculitis, [ENTITY_END] and arthritis in an individual lacking C5 (and its biologic functions), and (b) a remarkable propensity to bacterial infections in the proband, even during periods of low-dose or alternate-day corticosteroid therapy.',
              'gold_cui': {'MESH:D014657': {'cui': 'MESH:D014657',
                'name': 'Vasculitis',
                'types': 'Disease',
                'aliases': 'Angiitides|Angiitis|Vasculitides',
                'definition': 'Inflammation of any one of the blood vessels, including the ARTERIES; VEINS; and rest of the vasculature system in the body.'}},
              'predicted_cui': {'MESH:D056647': {'cui': 'MESH:D056647',
                'name': 'Systemic Vasculitis',
                'types': 'Disease',
                'aliases': 'Systemic Vasculitides|Vasculitides, Systemic|Vasculitis, Systemic',
                'definition': 'A heterogeneous group of diseases characterized by inflammation and necrosis of the blood vessel walls.'}}},
             '9360520.5': {'query_context': 'by progressive degeneration of the magnocellular neurons of the hypothalamus leading to decreased ability to produce the hormone arginine vasopressin (AVP). Affected individuals are not symptomatic at birth, but usually develop [ENTITY_START] diabetes insipidus [ENTITY_END] at 1-6 yr of age. The genetic locus of the disease is the AVP-neurophysin II (NPII) gene, and mutations that cause ADNDI have been found in both the signal peptide of',
              'gold_cui': {'MESH:D003919': {'cui': 'MESH:D003919',
                'name': 'Diabetes Insipidus',
                'types': 'Disease',
                'aliases': '',
                'definition': 'A disease that is characterized by frequent urination, excretion of large amounts of dilute URINE, and excessive THIRST. Etiologies of diabetes insipidus include deficiency of antidiuretic hormone (also known as ADH or VASOPRESSIN) secreted by the NEUROHYPOPHYSIS, impaired KIDNEY response to ADH, and impaired hypothalamic regulation of thirst.'}},
              'predicted_cui': {'MESH:D020790': {'cui': 'MESH:D020790',
                'name': 'Diabetes Insipidus, Neurogenic',
                'types': 'Disease',
                'aliases': 'CDI|Central Diabetes Insipidus|Diabetes Insipidus, Central|Diabetes Insipidus Cranial Type|Diabetes Insipidus, Cranial Type|Diabetes Insipidus, Neurohypophyseal|Diabetes Insipidus, Neurohypophyseal Type|Diabetes Insipidus, Pituitary|Diabetes Insipidus Primary Central|Diabetes Insipidus, Primary Central|Diabetes Insipidus Secondary To Vasopressin Deficiency|Neurogenic Diabetes Insipidus|Neurohypophyseal Diabetes Insipidus|Pituitary Diabetes Insipidus|Vasopressin Defective Diabetes Insipidus|Vasopressin Deficiency',
                'definition': 'A genetic or acquired polyuric disorder caused by a deficiency of VASOPRESSINS secreted by the NEUROHYPOPHYSIS. Clinical signs include the excretion of large volumes of dilute URINE; HYPERNATREMIA; THIRST; and polydipsia. Etiologies include HEAD TRAUMA; surgeries and diseases involving the HYPOTHALAMUS and the PITUITARY GLAND. This disorder may also be caused by mutations of genes such as ARVP encoding vasopressin and its corresponding neurophysin (NEUROPHYSINS).'}}},
             '9371490.3': {'query_context': 'Frequent inactivation of PTEN/MMAC1 in primary prostate cancer. Sporadic prostate carcinoma is the most common [ENTITY_START] male cancer [ENTITY_END] in the Western world, yet many of the major genetic events involved in the progression of this often fatal cancer remain to be elucidated. Numerous cytogenetic and allelotype studies have reported',
              'gold_cui': {'MESH:D005834': {'cui': 'MESH:D005834',
                'name': 'Genital Neoplasms, Male',
                'types': 'Disease',
                'aliases': 'Genital Neoplasm, Male|Male Genital Neoplasm|Male Genital Neoplasms|Neoplasm, Male Genital|Neoplasms, Male Genital',
                'definition': 'Tumor or cancer of the MALE GENITALIA.'}},
              'predicted_cui': {'MESH:D011471': {'cui': 'MESH:D011471',
                'name': 'Prostatic Neoplasms',
                'types': 'Disease',
                'aliases': 'Cancer of Prostate|Cancer of the Prostate|Cancer, Prostate|Cancer, Prostatic|Cancers, Prostate|Cancers, Prostatic|HPCQTL19|Neoplasm, Prostate|Neoplasm, Prostatic|Neoplasms, Prostate|Neoplasms, Prostatic|Prostate Cancer|PROSTATE CANCER AGGRESSIVENESS QUANTITATIVE TRAIT LOCUS ON CHROMOSOME 19|Prostate Cancers|Prostate Neoplasm|Prostate Neoplasms|Prostatic Cancer|Prostatic Cancers|Prostatic Neoplasm',
                'definition': 'Tumors or cancer of the PROSTATE.'}}},
             '9371490.4': {'query_context': 'primary prostate cancer. Sporadic prostate carcinoma is the most common male cancer in the Western world, yet many of the major genetic events involved in the progression of this often fatal [ENTITY_START] cancer [ENTITY_END] remain to be elucidated. Numerous cytogenetic and allelotype studies have reported frequent loss of heterozygosity on chromosomal arm 10q in sporadic prostate cancer. Deletion mapping studies have unambiguously identified a region',
              'gold_cui': {'MESH:D009369': {'cui': 'MESH:D009369',
                'name': 'Neoplasms',
                'types': 'Disease',
                'aliases': 'Benign Neoplasm|Benign Neoplasms|Cancer|Cancers|Malignancies|Malignancy|Malignant Neoplasm|Malignant Neoplasms|Neoplasia|Neoplasias|Neoplasm|Neoplasm, Benign|Neoplasm, Malignant|Neoplasms, Benign|Neoplasms, Malignant|Tumor|Tumors',
                'definition': 'New abnormal growth of tissue. Malignant neoplasms show a greater degree of anaplasia and have the properties of invasion and metastasis, compared to benign neoplasms.'}},
              'predicted_cui': {'MESH:D011471': {'cui': 'MESH:D011471',
                'name': 'Prostatic Neoplasms',
                'types': 'Disease',
                'aliases': 'Cancer of Prostate|Cancer of the Prostate|Cancer, Prostate|Cancer, Prostatic|Cancers, Prostate|Cancers, Prostatic|HPCQTL19|Neoplasm, Prostate|Neoplasm, Prostatic|Neoplasms, Prostate|Neoplasms, Prostatic|Prostate Cancer|PROSTATE CANCER AGGRESSIVENESS QUANTITATIVE TRAIT LOCUS ON CHROMOSOME 19|Prostate Cancers|Prostate Neoplasm|Prostate Neoplasms|Prostatic Cancer|Prostatic Cancers|Prostatic Neoplasm',
                'definition': 'Tumors or cancer of the PROSTATE.'}}},
             '9385378.5': {'query_context': 'A novel common missense mutation G301C in the N-acetylgalactosamine-6-sulfate sulfatase gene in mucopolysaccharidosis IVA. Mucopolysaccharidosis IVA (MPS IVA) is an autosomal recessive lysosomal storage disorder caused by a [ENTITY_START] genetic defect [ENTITY_END] in N-acetylgalactosamine-6-sulfate sulfatase (GALNS). In previous studies, we have found two common mutations in Caucasians and Japanese, respectively. To characterize the mutational spectrum in various ethnic groups, mutations in the GALNS',
              'gold_cui': {'MESH:D030342': {'cui': 'MESH:D030342',
                'name': 'Genetic Diseases, Inborn',
                'types': 'Disease',

In [31]:
mention_id = '9988281.10'
print(results13r[mention_id]["explanation"])

To determine the correct entity for the mention "ductal carcinomas," let's analyze the context and the candidate entities provided.

**Context Analysis:**
The context mentions "low-grade ductal carcinomas" and "high-grade ductal carcinomas." This suggests that the term "ductal carcinomas" is being used in the context of breast cancer, specifically referring to a type of breast cancer that originates in the ducts of the breast.

**Candidate Entities Analysis:**
1. **MESH:D044584 - Carcinoma, Ductal**
   - Definition: "Malignant neoplasms involving the ductal systems of any of a number of organs, such as the MAMMARY GLANDS, the PANCREAS, the PROSTATE, or the LACRIMAL GLAND."
   - This is too broad as it includes ductal carcinomas of other organs besides the breast.

2. **MESH:D018270 - Carcinoma, Ductal, Breast**
   - Definition: "An invasive (infiltrating) CARCINOMA of the mammary ductal system (MAMMARY GLANDS) in the human BREAST."
   - This definition aligns well with the context, specifically mentioning breast ductal carcinomas.

3. **MESH:D002277 - Carcinoma**
   - Definition: "A malignant neoplasm made up of epithelial cells tending to infiltrate the surrounding tissues and give rise to metastases."
   - This is a general term for carcinoma and does not specify ductal or breast.

4. **MESH:D021441 - Carcinoma, Pancreatic Ductal**
   - Definition: "Carcinoma that arises from the PANCREATIC DUCTS."
   - This is specific to pancreatic ductal carcinomas, not breast.

5. **MESH:D002583 - Uterine Cervical Neoplasms**
   - Definition: "Tumors or cancer of the UTERINE CERVIX."
   - This is specific to cervical cancer, not breast.

6. **MESH:D002822 - Choriocarcinoma**
   - Definition: "A malignant metastatic form of trophoblastic tumors."
   - This is specific to choriocarcinoma, not breast.

7. **MESH:D002295 - Carcinoma, Transitional Cell**
   - Definition: "A malignant neoplasm derived from TRANSITIONAL EPITHELIAL CELLS, occurring chiefly in the URINARY BLADDER; URETERS; or RENAL PELVIS."
   - This is specific to transitional cell carcinoma, not breast.

8. **MESH:D001943 - Breast Neoplasms**
   - Definition: "Tumors or cancer of the human BREAST."
   - This is a general term for breast cancer, not specific to ductal carcinomas.

9. **MESH:C562463 - Pancreatic Carcinoma**
   - Definition: "Pancreatic Acinar Carcinoma."
   - This is specific to pancreatic carcinoma, not breast.

10. **MESH:D018281 - Cholangiocarcinoma**
    - Definition: "A malignant tumor arising from the epithelium of the BILE DUCTS."
    - This is specific to bile duct cancer, not breast.

11. **MESH:D014594 - Uterine Neoplasms**
    - Definition: "Tumors or cancer of the UTERUS."
    - This is specific to uterine cancer, not breast.

12. **MESH:D002471 - Cell Transformation, Neoplastic**
    - Definition: "Cell changes manifested by escape from control mechanisms, increased growth potential, alterations in the cell surface, karyotypic abnormalities, morphological and biochemical deviations from the norm, and other attributes conferring the ability to invade, metastasize, and kill."
    - This is a general term for cell transformation, not specific to ductal carcinomas.

13. **MESH:D010051 - Ovarian Neoplasms**
    - Definition: "Tumors or cancer of the OVARY."
    - This is specific to ovarian cancer, not breast.

14. **MESH:C537535 - Secretory breast carcinoma**
    - Definition: "A condition in which abnormal cells have not spread outside the duct, lobule, or nipple to other tissues of the breast."
    - This is specific to secretory breast carcinoma, not ductal carcinomas.

15. **MESH:D000071960 - Breast Carcinoma In Situ**
    - Definition: "A condition in which abnormal cells have not spread outside the duct, lobule, or nipple to other tissues of the breast."
    - This is specific to carcinoma in situ, not ductal carcinomas.

16. **MESH:D000069295 - Mammary Analogue Secretory Carcinoma**
    - Definition: "A malignant neoplasm of epithelial cells of the SALIVARY GLANDS, with microcystic architecture, low-grade nuclei, and granular vacuolated cytoplasm."
    - This is specific to mammary analogue secretory carcinoma, not breast ductal carcinomas.

17. **MESH:D018267 - Carcinoma, Acinar Cell**
    - Definition: "A malignant tumor arising from secreting cells of a racemose gland, particularly the salivary glands."
    - This is specific to acinar cell carcinoma, not breast ductal carcinomas.

18. **MESH:D002578 - Uterine Cervical Dysplasia**
    - Definition: "Abnormal development of immature squamous EPITHELIAL CELLS of the UTERINE CERVIX."
    - This is specific to cervical dysplasia, not breast ductal carcinomas.

19. **MESH:D002280 - Carcinoma, Basal Cell**
    - Definition: "A malignant skin neoplasm that seldom metastasizes but has potentialities for local invasion and destruction."
    - This is specific to basal cell carcinoma, not breast ductal carcinomas.

20. **MESH:D018288 - Carcinoma, Small Cell**
    - Definition: "An anaplastic, highly malignant, and usually bronchogenic carcinoma composed of small ovoid cells with scanty neoplasm."
    - This is specific to small cell carcinoma, not breast ductal carcinomas.

**Conclusion:**
The most appropriate entity for "ductal carcinomas" in the context of breast cancer is **MESH:D018270 - Carcinoma, Ductal, Breast**.

Final Answer: **MESH:D018270**

## Result : Without reasoning

In [32]:
with open("data/biencoder/default2/Meta-Llama-3.1-8B-Instruct_k=3_results.json", "r") as f:
    results1 = json.load(f)
    
with open("data/biencoder/default2/Meta-Llama-3.1-8B-Instruct_k=5_results.json", "r") as f:
    results2 = json.load(f)
    
with open("data/biencoder/default2/Meta-Llama-3.1-8B-Instruct_k=10_results.json", "r") as f:
    results3 = json.load(f)
    
    
###############################################################  
with open("data/biencoder/default2/Mistral-7B-Instruct-v0.3_k=3_results.json", "r") as f:
    results4 = json.load(f)

with open("data/biencoder/default2/Mistral-7B-Instruct-v0.3_k=5_results.json", "r") as f:
    results5 = json.load(f)
    
with open("data/biencoder/default2/Mistral-7B-Instruct-v0.3_k=10_results.json", "r") as f:
    results6 = json.load(f)


###############################################################
with open("data/biencoder/default2/Mistral-Nemo-Instruct-2407_k=3_results.json", "r") as f:
    results7 = json.load(f)

with open("data/biencoder/default2/Mistral-Nemo-Instruct-2407_k=5_results.json", "r") as f:
    results8 = json.load(f)

with open("data/biencoder/default2/Mistral-Nemo-Instruct-2407_k=10_results.json", "r") as f:
    results9 = json.load(f)
    
###############################################################
with open("data/biencoder/default2/Qwen2.5-7B-Instruct_k=3_results.json", "r") as f:
    results10 = json.load(f)

with open("data/biencoder/default2/Qwen2.5-7B-Instruct_k=5_results.json", "r") as f:
    results11 = json.load(f)

with open("data/biencoder/default2/Qwen2.5-7B-Instruct_k=10_results.json", "r") as f:
    results12 = json.load(f)
    
    
###############################################################
with open("data/biencoder/default2/Qwen2.5-14B-Instruct_k=3_results.json", "r") as f:
    results13 = json.load(f)

with open("data/biencoder/default2/Qwen2.5-14B-Instruct_k=5_results.json", "r") as f:
    results14 = json.load(f)

with open("data/biencoder/default2/Qwen2.5-14B-Instruct_k=10_results.json", "r") as f:
    results15 = json.load(f)

In [33]:
score1 = scoring(results = results1, mention2gold = mention2gold)
print("data/default/Meta-Llama-3.1-8B-Instruct_k=3_results :", score1)
score2 = scoring(results = results2, mention2gold = mention2gold)
print("data/default/Meta-Llama-3.1-8B-Instruct_k=5_results:", score2)
score3 = scoring(results = results3, mention2gold = mention2gold)
print("data/default/Meta-Llama-3.1-8B-Instruct_k=10_results:", score3)

print("---------------------------------")

score4 = scoring(results = results4, mention2gold = mention2gold)
print("data/default/Mistral-7B-Instruct-v0.3_k=3_results :", score4)
score5 = scoring(results = results5, mention2gold = mention2gold)
print("data/default/Mistral-7B-Instruct-v0.3_k=5_results :", score5)
score6 = scoring(results = results6, mention2gold = mention2gold)
print("data/default/Mistral-7B-Instruct-v0.3_k=10_results :", score6)

print("---------------------------------")

score7 = scoring(results = results7, mention2gold = mention2gold)
print("data/default/Mistral-Nemo-Instruct-2407_k=3_results :", score7)
score8 = scoring(results = results8, mention2gold = mention2gold)
print("data/default/Mistral-Nemo-Instruct-2407_k=5_results:", score8)
score9 = scoring(results = results9, mention2gold = mention2gold)
print("data/default/Mistral-Nemo-Instruct-2407_k=10_results:", score9)

print("---------------------------------")

score10 = scoring(results = results10, mention2gold = mention2gold)
print("data/default/Qwen2.5-7B-Instruct_k=3_results :", score10)
score11 = scoring(results = results11, mention2gold = mention2gold)
print("data/default/Qwen2.5-7B-Instruct_k=5_results:", score11)
score12 = scoring(results = results12, mention2gold = mention2gold)
print("data/default/Qwen2.5-7B-Instruct_k=10_results:", score12)

print("---------------------------------")

score13 = scoring(results = results13, mention2gold = mention2gold)
print("data/default/Qwen2.5-14B-Instruct_k=3_results :", score13)
score14 = scoring(results = results14, mention2gold = mention2gold)
print("data/default/Qwen2.5-14B-Instruct_k=5_results:", score14)
score15 = scoring(results = results15, mention2gold = mention2gold)
print("data/default/Qwen2.5-14B-Instruct_k=10_results:", score15)

data/default/Meta-Llama-3.1-8B-Instruct_k=3_results : 0.8775
data/default/Meta-Llama-3.1-8B-Instruct_k=5_results: 0.8825
data/default/Meta-Llama-3.1-8B-Instruct_k=10_results: 0.89375
---------------------------------
data/default/Mistral-7B-Instruct-v0.3_k=3_results : 0.8275
data/default/Mistral-7B-Instruct-v0.3_k=5_results : 0.8275
data/default/Mistral-7B-Instruct-v0.3_k=10_results : 0.8375
---------------------------------
data/default/Mistral-Nemo-Instruct-2407_k=3_results : 0.87
data/default/Mistral-Nemo-Instruct-2407_k=5_results: 0.89125
data/default/Mistral-Nemo-Instruct-2407_k=10_results: 0.9
---------------------------------
data/default/Qwen2.5-7B-Instruct_k=3_results : 0.90625
data/default/Qwen2.5-7B-Instruct_k=5_results: 0.90875
data/default/Qwen2.5-7B-Instruct_k=10_results: 0.8975
---------------------------------
data/default/Qwen2.5-14B-Instruct_k=3_results : 0.8925
data/default/Qwen2.5-14B-Instruct_k=5_results: 0.9
data/default/Qwen2.5-14B-Instruct_k=10_results: 0.89125

In [34]:
def pooled_scoring(results, mention2gold):
    """
    Return the score of the model.
    -------
    results : list of dictionaries [{mention_id : {"predicted" : predicted CUI, "explanation" : explanation}}, ...]
    mention2gold : dictionary {mention_id : gold CUI or list of gold CUIs}
    """
    score = 0
    found_mentions = set()  # To track which mentions have already been correctly predicted

    # Iterate over each set of predictions (each result_i)
    for result in results:
        for mention_id, value in result.items():
            if mention_id in found_mentions:
                continue  # Skip if this mention was already counted
            
            predicted_cui = value["predicted"]
            gold_cuis = mention2gold[mention_id]  # Gold CUI or list of CUIs
            
            # Ensure gold_cuis is a list for consistent comparison
            if not isinstance(gold_cuis, list):
                gold_cuis = [gold_cuis]

            # Check if the predicted CUI is correct
            if predicted_cui in gold_cuis:
                score += 1  # Increment score only once per mention_id
                found_mentions.add(mention_id)  # Mark this mention as found

    return score / len(mention2gold)

In [77]:
results = [
    results1, 
    # results2, 
    # results3,    
    results4, 
    # results5, 
    # results6,
    results7, 
    # results8, 
    # results9,
    results10, 
    # results11, 
    # results12,
    results13, 
    # results14, 
    # results15,
    ]
score = pooled_scoring(results, mention2gold)
score

0.9473684210526315

In [ ]:
results_r = [
    results1r, 
    # results2r, 
    # results3r,    
    results4r, 
    # results5r, 
    # results6r,
    results7r, 
    # results8r, 
    # results9r,
    results10r, 
    # results11r, 
    # results12r,
    results13r, 
    # results14r, 
    # results15r,
    ]
score_r = pooled_scoring(results_r, mention2gold)
score_r

In [42]:
# len(results)
# len(mention2gold)

In [43]:
error_mentions = error_analysis(results = results2, 
                                ontology = ontology2, 
                                mention2gold = mention2gold, 
                                mention2context = mention2context)
error_mentions

defaultdict(dict,
            {'9288106.2': {'query_context': 'Clustering of missense mutations in the ataxia-telangiectasia gene in a [ENTITY_START] sporadic T-cell leukaemia. [ENTITY_END] Ataxia-telangiectasia (A-T) is a recessive multi-system disorder caused by mutations in the ATM gene at 11q22-q23 (ref. 3). The risk of cancer, especially lymphoid neoplasias, is substantially elevated in A-T',
              'gold_cui': {'MESH:D015458': {'cui': 'MESH:D015458',
                'name': 'Leukemia, T-Cell',
                'types': 'Disease',
                'aliases': 'Leukemia, Lymphocytic, T Cell|Leukemia, Lymphocytic, T-Cell|Leukemias, T-Cell|Leukemias, T-Cell Lymphocytic|Leukemias, T Lymphocytic|Leukemias, T-Lymphocytic|Leukemia, T Cell|Leukemia, T-Cell Lymphocytic|Leukemia, T Lymphocytic|Leukemia, T-Lymphocytic|Lymphocytic Leukemias, T|Lymphocytic Leukemias, T-Cell|Lymphocytic Leukemia, T|Lymphocytic Leukemia, T Cell|Lymphocytic Leukemia, T-Cell|T Cell Leukemia|T-Cell Leukemia|T-Cell Leukemias|T-Cell Lymphocytic Leukemia|T-Cell Lymphocytic Leukemias|T Lymphocytic Leukemia|T-Lymphocytic Leukemia|T Lymphocytic Leukemias|T-Lymphocytic Leukemias',
                'definition': 'A malignant disease of the T-LYMPHOCYTES in the bone marrow, thymus, and/or blood.'}},
              'predicted_cui': {'MESH:D016399': {'cui': 'MESH:D016399',
                'name': 'Lymphoma, T-Cell',
                'types': 'Disease',
                'aliases': 'Lymphomas, T-Cell|Lymphoma, T Cell|T Cell Lymphoma|T-Cell Lymphoma|T-Cell Lymphomas',
                'definition': 'A group of heterogeneous lymphoid tumors representing malignant transformations of T-lymphocytes.'}}},
             '9288106.5': {'query_context': 'Clustering of missense mutations in the ataxia-telangiectasia gene in a sporadic T-cell leukaemia. Ataxia-telangiectasia (A-T) is a [ENTITY_START] recessive multi-system disorder [ENTITY_END] caused by mutations in the ATM gene at 11q22-q23 (ref. 3). The risk of cancer, especially lymphoid neoplasias, is substantially elevated in A-T patients and has long been associated with',
              'gold_cui': {'MESH:D030342': {'cui': 'MESH:D030342',
                'name': 'Genetic Diseases, Inborn',
                'types': 'Disease',
                'aliases': 'Defect, Single-Gene|Defects, Single-Gene|Disease, Genetic|Disease, Hereditary|Disease, Inborn Genetic|Diseases, Genetic|Diseases, Hereditary|Diseases, Inborn Genetic|Disorder, Genetic|Disorders, Genetic|Genetic Disease|Genetic Disease, Inborn|Genetic Diseases|Genetic Disorder|Genetic Disorders|Hereditary Disease|Hereditary Diseases|Inborn Genetic Disease|Inborn Genetic Diseases|Single-Gene Defect|Single Gene Defects|Single-Gene Defects',
                'definition': "Diseases that are caused by genetic mutations present during embryo or fetal development, although they may be observed later in life. The mutations may be inherited from a parent's genome or they may be acquired in utero."}},
              'predicted_cui': {'MESH:D009358': {'cui': 'MESH:D009358',
                'name': 'Congenital, Hereditary, and Neonatal Diseases and Abnormalities',
                'types': 'Disease',
                'aliases': 'Congenital Disorder|Congenital Disorders|Disorder, Congenital|Disorders, Congenital|Neonatal Diseases and Abnormalities',
                'definition': 'Diseases existing at birth and often before birth, or that develop during the first month of life (INFANT, NEWBORN, DISEASES), regardless of causation. Of these diseases, those characterized by structural deformities are termed CONGENITAL ABNORMALITIES.'}}},
             '9288106.10': {'query_context': '(ref. 3). The risk of cancer, especially lymphoid neoplasias, is substantially elevated in A-T patients and has long been associated with chromosomal instability. By analysing tumour DNA from patients with [ENTITY_START] sporadic T-cell prolymphocytic leukaemia [ENTITY_END] (T-PLL), a rare clonal malignancy with similarities to a mature T-cell leukaemia seen in A-T, we demonstrate a high frequency of ATM mutations in T-PLL. In marked contrast to the',
              'gold_cui': {'MESH:D015461': {'cui': 'MESH:D015461',
                'name': 'Leukemia, Prolymphocytic, T-Cell',
                'types': 'Disease',
                'aliases': 'Leukemia, Lymphocytic, Chronic, T Cell|Leukemia, Lymphocytic, Chronic, T-Cell|Leukemias, T-Cell Prolymphocytic|Leukemia, T Cell, Chronic|Leukemia, T-Cell, Chronic|Leukemia, T-Cell Prolymphocytic|Lymphocytic Leukemia, T Cell, Chronic|Lymphocytic Leukemia, T-Cell, Chronic|Prolymphocytic Leukemias, T-Cell|Prolymphocytic Leukemia, T-Cell|T-Cell Leukemia, Chronic|T Cell Prolymphocytic Leukemia|T-Cell Prolymphocytic Leukemia|T-Cell Prolymphocytic Leukemias|T-Lymphocytic Leukemia, Chronic',
                'definition': 'A lymphoid leukemia characterized by a profound LYMPHOCYTOSIS with or without LYMPHADENOPATHY, hepatosplenomegaly, frequently rapid progression, and short survival. It was formerly called T-cell chronic lymphocytic leukemia.'}},
              'predicted_cui': {'MESH:D016399': {'cui': 'MESH:D016399',
                'name': 'Lymphoma, T-Cell',
                'types': 'Disease',
                'aliases': 'Lymphomas, T-Cell|Lymphoma, T Cell|T Cell Lymphoma|T-Cell Lymphoma|T-Cell Lymphomas',
                'definition': 'A group of heterogeneous lymphoid tumors representing malignant transformations of T-lymphocytes.'}}},
             '9288106.22': {'query_context': 'In contrast, no mutations were detected in the p53 gene, suggesting that this tumour suppressor is not frequently altered in this leukaemia. Occasional missense mutations in ATM were also found in [ENTITY_START] tumour [ENTITY_END] DNA from patients with B-cell non-Hodgkins lymphomas (B-NHL) and a B-NHL cell line. The evidence of a significant proportion of loss-of-function mutations and a complete absence of the normal copy of',
              'gold_cui': {'MESH:D009369': {'cui': 'MESH:D009369',
                'name': 'Neoplasms',
                'types': 'Disease',
                'aliases': 'Benign Neoplasm|Benign Neoplasms|Cancer|Cancers|Malignancies|Malignancy|Malignant Neoplasm|Malignant Neoplasms|Neoplasia|Neoplasias|Neoplasm|Neoplasm, Benign|Neoplasm, Malignant|Neoplasms, Benign|Neoplasms, Malignant|Tumor|Tumors',
                'definition': 'New abnormal growth of tissue. Malignant neoplasms show a greater degree of anaplasia and have the properties of invasion and metastasis, compared to benign neoplasms.'}},
              'predicted_cui': {'MESH:D008223': {'cui': 'MESH:D008223',
                'name': 'Lymphoma',
                'types': 'Disease',
                'aliases': 'Germinoblastic Sarcoma|Germinoblastic Sarcomas|Germinoblastoma|Germinoblastomas|Lymphoma, Malignant|Lymphomas|Lymphomas, Malignant|Malignant Lymphoma|Malignant Lymphomas|Reticulolymphosarcoma|Reticulolymphosarcomas|Sarcoma, Germinoblastic|Sarcomas, Germinoblastic',
                'definition': 'A general term for various neoplastic diseases of the lymphoid tissue.'}}},
             '9288106.23': {'query_context': 'in the p53 gene, suggesting that this tumour suppressor is not frequently altered in this leukaemia. Occasional missense mutations in ATM were also found in tumour DNA from patients with [ENTITY_START] B-cell non-Hodgkins lymphomas [ENTITY_END] (B-NHL) and a B-NHL cell line. The evidence of a significant proportion of loss-of-function mutations and a complete absence of the normal copy of ATM in the majority of mutated',
              'gold_cui': {'MESH:D016393': {'cui': 'MESH:D016393',
                'name': 'Lymphoma, B-Cell',
                'types': 'Disease',
                'aliases': 'B Cell Lymphoma|B-Cell Lymphoma|B-Cell Lymphomas|Lymphoma, B Cell|Lymphomas, B-Cell',
                'definition': 'A group of heterogeneous lymphoid tumors generally expressing one or more B-cell antigens or representing malignant transformations of B-lymphocytes.'}},
              'predicted_cui': {'MESH:D008228': {'cui': 'MESH:D008228',
                'name': 'Lymphoma, Non-Hodgkin',
                'types': 'Disease',
                'aliases': "Diffuse Lymphoma|Diffuse Lymphomas|Diffuse Mixed Cell Lymphoma|Diffuse Mixed-Cell Lymphoma|Diffuse Mixed-Cell Lymphomas|Diffuse Mixed Small and Large Cell Lymphoma|Diffuse Small Cleaved Cell Lymphoma|Diffuse Small Cleaved-Cell Lymphoma|Diffuse Undifferentiated Lymphoma|Diffuse Undifferentiated Lymphomas|High-Grade Lymphoma|High-Grade Lymphomas|Intermediate-Grade Lymphoma|Intermediate-Grade Lymphomas|Low-Grade Lymphoma|Low-Grade Lymphomas|Lymphatic Sarcoma|Lymphatic Sarcomas|Lymphocytic-Histiocytic Lymphoma, Mixed|Lymphocytic-Histiocytic Lymphomas, Mixed|Lymphoma, Atypical Diffuse Small Lymphoid|Lymphoma, Diffuse|Lymphoma, Diffuse Mixed-Cell|Lymphoma, Diffuse, Mixed Lymphocytic-Histiocytic|Lymphoma, Diffuse Undifferentiated|Lymphoma, High Grade|Lymphoma, High-Grade|Lymphoma, Intermediate Grade|Lymphoma, Intermediate-Grade|Lymphoma, Low Grade|Lymphoma, Low-Grade|Lymphoma, Mixed|Lymphoma, Mixed Cell|Lymphoma, Mixed-Cell|Lymphoma, Mixed Cell, Diffuse|Lymphoma, Mixed-Cell, Diffuse|Lymphoma, Mixed Lymphocytic Histiocytic|Lymphoma, Mixed Lymphocytic-Histiocytic|Lymphoma, Mixed Small and Large Cell, Diffuse|Lymphoma, Nonhodgkin|Lymphoma, Non Hodgkin|Lymphoma, Non-Hodgkin, Familial|Lymphoma, Nonhodgkins|Lymphoma, Nonhodgkin's|Lymphoma, Non Hodgkins|Lymphoma, Non Hodgkin's|Lymphoma, Non-Hodgkins|Lymphoma, Non-Hodgkin's|Lymphoma, Pleomorphic|Lymphoma, Small and Large Cleaved-Cell, Diffuse|Lymphoma, Small Cleaved Cell, Diffuse|Lymphoma, Small Cleaved-Cell, Diffuse|Lymphoma, Small Noncleaved Cell|Lymphoma, Small Noncleaved-Cell|Lymphoma, Small Non Cleaved Cell|Lymphoma, Small Non-Cleaved-Cell|Lymphoma, Undifferentiated|Lymphoma, Undifferentiated, Diffuse|Lymphosarcoma|Lymphosarcomas|Mixed Cell Lymphoma|Mixed-Cell Lymphoma|Mixed Cell Lymphoma, Diffuse|Mixed-Cell Lymphoma, Diffuse|Mixed-Cell Lymphomas|Mixed Lymphocytic-Histiocytic Lymphoma|Mixed Lymphocytic-Histiocytic Lymphomas|Mixed Lymphoma|Mixed Lymphomas|Mixed Small and Large Cell Lymphoma, Diffuse|NHL|Noncleaved-Cell Lymphoma, Small|Non-Cleaved-Cell Lymphoma, Small|Non Hodgkin Lymphoma|Non-Hodgkin Lymphoma|Nonhodgkin's Lymphoma|Nonhodgkins Lymphoma|Non Hodgkin's Lymphoma|Non-Hodgkin's Lymphoma|Non-Hodgkins Lymphoma|Pleomorphic Lymphoma|Pleomorphic Lymphomas|Reticulosarcoma|Reticulosarcomas|Reticulum Cell Sarcoma|Reticulum-Cell Sarcoma|Reticulum Cell Sarcomas|Reticulum-Cell Sarcomas|Sarcoma, Lymphatic|Sarcoma, Reticulum Cell|Sarcoma, Reticulum-Cell|Small Cleaved Cell Lymphoma, Diffuse|Small Cleaved-Cell Lymphoma, Diffuse|Small Noncleaved Cell Lymphoma|Small Noncleaved-Cell Lymphoma|Small Non Cleaved Cell Lymphoma|Small Non-Cleaved-Cell Lymphoma|Small Noncleaved-Cell Lymphomas|Small Non-Cleaved-Cell Lymphomas|Undifferentiated Lymphoma|Undifferentiated Lymphoma, Diffuse|Undifferentiated Lymphomas",
                'definition': "Any of a group of malignant tumors of lymphoid tissue that differ from HODGKIN DISEASE, being more heterogeneous with respect to malignant cell lineage, clinical course, prognosis, and therapy. The only common feature among these tumors is the absence of giant REED-STERNBERG CELLS, a characteristic of Hodgkin's disease."}}},
             '9288106.24': {'query_context': 'p53 gene, suggesting that this tumour suppressor is not frequently altered in this leukaemia. Occasional missense mutations in ATM were also found in tumour DNA from patients with B-cell non-Hodgkins lymphomas [ENTITY_START] (B-NHL) [ENTITY_END] and a B-NHL cell line. The evidence of a significant proportion of loss-of-function mutations and a complete absence of the normal copy of ATM in the majority of mutated tumours establishes',
              'gold_cui': {'MESH:D016393': {'cui': 'MESH:D016393',
                'name': 'Lymphoma, B-Cell',
                'types': 'Disease',
                'aliases': 'B Cell Lymphoma|B-Cell Lymphoma|B-Cell Lymphomas|Lymphoma, B Cell|Lymphomas, B-Cell',
                'definition': 'A group of heterogeneous lymphoid tumors generally expressing one or more B-cell antigens or representing malignant transformations of B-lymphocytes.'}},
              'predicted_cui': {'MESH:D008228': {'cui': 'MESH:D008228',
                'name': 'Lymphoma, Non-Hodgkin',
                'types': 'Disease',
                'aliases': "Diffuse Lymphoma|Diffuse Lymphomas|Diffuse Mixed Cell Lymphoma|Diffuse Mixed-Cell Lymphoma|Diffuse Mixed-Cell Lymphomas|Diffuse Mixed Small and Large Cell Lymphoma|Diffuse Small Cleaved Cell Lymphoma|Diffuse Small Cleaved-Cell Lymphoma|Diffuse Undifferentiated Lymphoma|Diffuse Undifferentiated Lymphomas|High-Grade Lymphoma|High-Grade Lymphomas|Intermediate-Grade Lymphoma|Intermediate-Grade Lymphomas|Low-Grade Lymphoma|Low-Grade Lymphomas|Lymphatic Sarcoma|Lymphatic Sarcomas|Lymphocytic-Histiocytic Lymphoma, Mixed|Lymphocytic-Histiocytic Lymphomas, Mixed|Lymphoma, Atypical Diffuse Small Lymphoid|Lymphoma, Diffuse|Lymphoma, Diffuse Mixed-Cell|Lymphoma, Diffuse, Mixed Lymphocytic-Histiocytic|Lymphoma, Diffuse Undifferentiated|Lymphoma, High Grade|Lymphoma, High-Grade|Lymphoma, Intermediate Grade|Lymphoma, Intermediate-Grade|Lymphoma, Low Grade|Lymphoma, Low-Grade|Lymphoma, Mixed|Lymphoma, Mixed Cell|Lymphoma, Mixed-Cell|Lymphoma, Mixed Cell, Diffuse|Lymphoma, Mixed-Cell, Diffuse|Lymphoma, Mixed Lymphocytic Histiocytic|Lymphoma, Mixed Lymphocytic-Histiocytic|Lymphoma, Mixed Small and Large Cell, Diffuse|Lymphoma, Nonhodgkin|Lymphoma, Non Hodgkin|Lymphoma, Non-Hodgkin, Familial|Lymphoma, Nonhodgkins|Lymphoma, Nonhodgkin's|Lymphoma, Non Hodgkins|Lymphoma, Non Hodgkin's|Lymphoma, Non-Hodgkins|Lymphoma, Non-Hodgkin's|Lymphoma, Pleomorphic|Lymphoma, Small and Large Cleaved-Cell, Diffuse|Lymphoma, Small Cleaved Cell, Diffuse|Lymphoma, Small Cleaved-Cell, Diffuse|Lymphoma, Small Noncleaved Cell|Lymphoma, Small Noncleaved-Cell|Lymphoma, Small Non Cleaved Cell|Lymphoma, Small Non-Cleaved-Cell|Lymphoma, Undifferentiated|Lymphoma, Undifferentiated, Diffuse|Lymphosarcoma|Lymphosarcomas|Mixed Cell Lymphoma|Mixed-Cell Lymphoma|Mixed Cell Lymphoma, Diffuse|Mixed-Cell Lymphoma, Diffuse|Mixed-Cell Lymphomas|Mixed Lymphocytic-Histiocytic Lymphoma|Mixed Lymphocytic-Histiocytic Lymphomas|Mixed Lymphoma|Mixed Lymphomas|Mixed Small and Large Cell Lymphoma, Diffuse|NHL|Noncleaved-Cell Lymphoma, Small|Non-Cleaved-Cell Lymphoma, Small|Non Hodgkin Lymphoma|Non-Hodgkin Lymphoma|Nonhodgkin's Lymphoma|Nonhodgkins Lymphoma|Non Hodgkin's Lymphoma|Non-Hodgkin's Lymphoma|Non-Hodgkins Lymphoma|Pleomorphic Lymphoma|Pleomorphic Lymphomas|Reticulosarcoma|Reticulosarcomas|Reticulum Cell Sarcoma|Reticulum-Cell Sarcoma|Reticulum Cell Sarcomas|Reticulum-Cell Sarcomas|Sarcoma, Lymphatic|Sarcoma, Reticulum Cell|Sarcoma, Reticulum-Cell|Small Cleaved Cell Lymphoma, Diffuse|Small Cleaved-Cell Lymphoma, Diffuse|Small Noncleaved Cell Lymphoma|Small Noncleaved-Cell Lymphoma|Small Non Cleaved Cell Lymphoma|Small Non-Cleaved-Cell Lymphoma|Small Noncleaved-Cell Lymphomas|Small Non-Cleaved-Cell Lymphomas|Undifferentiated Lymphoma|Undifferentiated Lymphoma, Diffuse|Undifferentiated Lymphomas",
                'definition': "Any of a group of malignant tumors of lymphoid tissue that differ from HODGKIN DISEASE, being more heterogeneous with respect to malignant cell lineage, clinical course, prognosis, and therapy. The only common feature among these tumors is the absence of giant REED-STERNBERG CELLS, a characteristic of Hodgkin's disease."}}},
             '9288106.25': {'query_context': 'that this tumour suppressor is not frequently altered in this leukaemia. Occasional missense mutations in ATM were also found in tumour DNA from patients with B-cell non-Hodgkins lymphomas (B-NHL) and a [ENTITY_START] B-NHL [ENTITY_END] cell line. The evidence of a significant proportion of loss-of-function mutations and a complete absence of the normal copy of ATM in the majority of mutated tumours establishes somatic inactivation of',
              'gold_cui': {'MESH:D016393': {'cui': 'MESH:D016393',
                'name': 'Lymphoma, B-Cell',
                'types': 'Disease',
                'aliases': 'B Cell Lymphoma|B-Cell Lymphoma|B-Cell Lymphomas|Lymphoma, B Cell|Lymphomas, B-Cell',
                'definition': 'A group of heterogeneous lymphoid tumors generally expressing one or more B-cell antigens or representing malignant transformations of B-lymphocytes.'}},
              'predicted_cui': {'MESH:D008228': {'cui': 'MESH:D008228',
                'name': 'Lymphoma, Non-Hodgkin',
                'types': 'Disease',
                'aliases': "Diffuse Lymphoma|Diffuse Lymphomas|Diffuse Mixed Cell Lymphoma|Diffuse Mixed-Cell Lymphoma|Diffuse Mixed-Cell Lymphomas|Diffuse Mixed Small and Large Cell Lymphoma|Diffuse Small Cleaved Cell Lymphoma|Diffuse Small Cleaved-Cell Lymphoma|Diffuse Undifferentiated Lymphoma|Diffuse Undifferentiated Lymphomas|High-Grade Lymphoma|High-Grade Lymphomas|Intermediate-Grade Lymphoma|Intermediate-Grade Lymphomas|Low-Grade Lymphoma|Low-Grade Lymphomas|Lymphatic Sarcoma|Lymphatic Sarcomas|Lymphocytic-Histiocytic Lymphoma, Mixed|Lymphocytic-Histiocytic Lymphomas, Mixed|Lymphoma, Atypical Diffuse Small Lymphoid|Lymphoma, Diffuse|Lymphoma, Diffuse Mixed-Cell|Lymphoma, Diffuse, Mixed Lymphocytic-Histiocytic|Lymphoma, Diffuse Undifferentiated|Lymphoma, High Grade|Lymphoma, High-Grade|Lymphoma, Intermediate Grade|Lymphoma, Intermediate-Grade|Lymphoma, Low Grade|Lymphoma, Low-Grade|Lymphoma, Mixed|Lymphoma, Mixed Cell|Lymphoma, Mixed-Cell|Lymphoma, Mixed Cell, Diffuse|Lymphoma, Mixed-Cell, Diffuse|Lymphoma, Mixed Lymphocytic Histiocytic|Lymphoma, Mixed Lymphocytic-Histiocytic|Lymphoma, Mixed Small and Large Cell, Diffuse|Lymphoma, Nonhodgkin|Lymphoma, Non Hodgkin|Lymphoma, Non-Hodgkin, Familial|Lymphoma, Nonhodgkins|Lymphoma, Nonhodgkin's|Lymphoma, Non Hodgkins|Lymphoma, Non Hodgkin's|Lymphoma, Non-Hodgkins|Lymphoma, Non-Hodgkin's|Lymphoma, Pleomorphic|Lymphoma, Small and Large Cleaved-Cell, Diffuse|Lymphoma, Small Cleaved Cell, Diffuse|Lymphoma, Small Cleaved-Cell, Diffuse|Lymphoma, Small Noncleaved Cell|Lymphoma, Small Noncleaved-Cell|Lymphoma, Small Non Cleaved Cell|Lymphoma, Small Non-Cleaved-Cell|Lymphoma, Undifferentiated|Lymphoma, Undifferentiated, Diffuse|Lymphosarcoma|Lymphosarcomas|Mixed Cell Lymphoma|Mixed-Cell Lymphoma|Mixed Cell Lymphoma, Diffuse|Mixed-Cell Lymphoma, Diffuse|Mixed-Cell Lymphomas|Mixed Lymphocytic-Histiocytic Lymphoma|Mixed Lymphocytic-Histiocytic Lymphomas|Mixed Lymphoma|Mixed Lymphomas|Mixed Small and Large Cell Lymphoma, Diffuse|NHL|Noncleaved-Cell Lymphoma, Small|Non-Cleaved-Cell Lymphoma, Small|Non Hodgkin Lymphoma|Non-Hodgkin Lymphoma|Nonhodgkin's Lymphoma|Nonhodgkins Lymphoma|Non Hodgkin's Lymphoma|Non-Hodgkin's Lymphoma|Non-Hodgkins Lymphoma|Pleomorphic Lymphoma|Pleomorphic Lymphomas|Reticulosarcoma|Reticulosarcomas|Reticulum Cell Sarcoma|Reticulum-Cell Sarcoma|Reticulum Cell Sarcomas|Reticulum-Cell Sarcomas|Sarcoma, Lymphatic|Sarcoma, Reticulum Cell|Sarcoma, Reticulum-Cell|Small Cleaved Cell Lymphoma, Diffuse|Small Cleaved-Cell Lymphoma, Diffuse|Small Noncleaved Cell Lymphoma|Small Noncleaved-Cell Lymphoma|Small Non Cleaved Cell Lymphoma|Small Non-Cleaved-Cell Lymphoma|Small Noncleaved-Cell Lymphomas|Small Non-Cleaved-Cell Lymphomas|Undifferentiated Lymphoma|Undifferentiated Lymphoma, Diffuse|Undifferentiated Lymphomas",
                'definition': "Any of a group of malignant tumors of lymphoid tissue that differ from HODGKIN DISEASE, being more heterogeneous with respect to malignant cell lineage, clinical course, prognosis, and therapy. The only common feature among these tumors is the absence of giant REED-STERNBERG CELLS, a characteristic of Hodgkin's disease."}}},

In [59]:
with open(
    "data/crossencoder/recall/Meta-Llama-3.1-8B-Instruct_k=3_results.json", "r"
) as f:
    results = json.load(f)

In [60]:
recall_r = recall_fn(results=results, mention2gold=mention2gold, ks = list(range(1,6)))
recall_r

{'recall@1': 0.8738396624472573,
 'recall@2': 0.9381856540084389,
 'recall@3': 0.9609704641350211,
 'recall@4': 0.9698312236286919,
 'recall@5': 0.9761603375527426}

In [61]:
unnormalized_recall = {
    f"unnormalized_{k}": v * number_hits_crossencoder[20] / 960
    for k, v in recall_r.items()
}
unnormalized_recall

{'unnormalized_recall@1': 0.731840717299578,
 'unnormalized_recall@2': 0.7857304852320676,
 'unnormalized_recall@3': 0.8048127637130802,
 'unnormalized_recall@4': 0.8122336497890295,
 'unnormalized_recall@5': 0.8175342827004218}

# vllm + aqlm

In [41]:
llm = LLM(
    model="ISTA-DASLab/Mixtral-8x7B-Instruct-v0_1-AQLM-2Bit-1x16-hf",
    enforce_eager=True,
)

tokenizer = llm.get_tokenizer()

WARNING 09-12 18:51:54 config.py:330] aqlm quantization is not fully optimized yet. The speed can be slower than non-quantized models.
WARNING 09-12 18:51:54 config.py:378] To see benefits of async output processing, enable CUDA graph. Since, enforce-eager is enabled, async output processor cannot be used
INFO 09-12 18:51:54 llm_engine.py:213] Initializing an LLM engine (v0.6.0) with config: model='ISTA-DASLab/Mixtral-8x7B-Instruct-v0_1-AQLM-2Bit-1x16-hf', speculative_config=None, tokenizer='ISTA-DASLab/Mixtral-8x7B-Instruct-v0_1-AQLM-2Bit-1x16-hf', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=32768, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=aqlm, enforce_eager=True, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=ISTA-DASLab/Mixtral-8x7B-Instruct-v0_1-AQLM-2Bit-1x16-hf, use_v2_block_manager=False, num_scheduler_steps=1, enable_prefix_caching=False, use_async_output_proc=False)
INFO 09-12 18:51:55 selector.py:217] Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
INFO 09-12 18:51:55 selector.py:116] Using XFormers backend.

/nethome/cye73/conda_envs/bioel/lib/python3.9/site-packages/xformers/ops/fmha/flash.py:211: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_fwd")
/nethome/cye73/conda_envs/bioel/lib/python3.9/site-packages/xformers/ops/fmha/flash.py:344: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_bwd")

INFO 09-12 18:52:04 model_runner.py:915] Starting to load model ISTA-DASLab/Mixtral-8x7B-Instruct-v0_1-AQLM-2Bit-1x16-hf...
INFO 09-12 18:52:04 selector.py:217] Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
INFO 09-12 18:52:04 selector.py:116] Using XFormers backend.
INFO 09-12 18:52:04 weight_utils.py:236] Using model weights format ['*.safetensors']

Loading safetensors checkpoint shards:   0% Completed | 0/3 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  33% Completed | 1/3 [00:03<00:06,  3.10s/it]
Loading safetensors checkpoint shards:  67% Completed | 2/3 [00:06<00:03,  3.53s/it]
Loading safetensors checkpoint shards: 100% Completed | 3/3 [00:09<00:00,  3.32s/it]
Loading safetensors checkpoint shards: 100% Completed | 3/3 [00:09<00:00,  3.33s/it]

INFO 09-12 18:52:16 model_runner.py:926] Loading model weights took 12.2120 GB
INFO 09-12 18:52:45 gpu_executor.py:122] # GPU blocks: 11939, # CPU blocks: 2048

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

In [30]:
# def prompt_vllm_aqlm(mention, context, system_instructions, candidates, topk_examples, llm, tokenizer, sampling_params):
#     ''' 
#     mention : str (name of the mention to be linked)
#     context : str (context where the mention appears)
#     system_instructions : str (instructions for the LLM)
#     candidates : list of list of CUIs : [[cui1], [cui2, cui3], ...]
#     topk_examples : str (top k examples of similar contexts)
#     llm : LLM model
#     tokenizer : AutoTokenizer
#     sampling_params : SamplingParams config
#     '''
    
#     prompt_text = f"""
#     System Instructions: {system_instructions} \n
    
#     Here are a few examples: \n
#     {topk_examples} \n

#     This is the specific mention that needs to be linked to the correct entity: {mention} \n

#     This is the context where the mention appears: \n
#     {context} \n
    
#     These are the candidate entities to choose from: \n
#     {candidates} \n
    
#     You MUST PROVIDE an ANSWER among the candidates. \n

#     Return the answer in the following format: CUI
#     For instance : "MESH:D000000" "OMIM:000000" are valid answers. \n
#     Do not add provide any explanations ! But you MUST give ONE answer.
#     """
#     conversations = tokenizer.apply_chat_template(
#         [{'role': 'user', 'content': prompt_text}],
#         tokenize=False,
#     )

#     # Decode the generated tokens into text
#     outputs = llm.generate([conversations], sampling_params=sampling_params, use_tqdm=False)
#     answer = outputs[0].outputs[0].text

#     return answer

In [43]:
mention = "9931324.1"
text = mention2text[mention]
context = mention2context[mention]
candidates = get_candidates_data(mention2biencoder_candidates[mention], ontology2)
topk = topk_examples(model = model,
                    index = index,
                    query=context, 
                    corpus=corpus, 
                    TrainMap_context2mention=TrainMap_context2mention, 
                    train_mention2text=train_mention2text, 
                    train_mention2gold=train_mention2gold, 
                    ontology=ontology2, 
                    k=3)

pred_cui = prompt_vllm_aqlm(mention=text, 
                       context=context, 
                       system_instructions=system_instructions,
                       candidates=candidates, 
                       topk_examples=topk,
                       llm=llm,
                       tokenizer=tokenizer,
                       sampling_params=sampling_params)

# Output the results
print("Mention ID:", mention)
print("Context:", context)
print("Top k examples:", topk)
print("Text:", mention2text[mention])
print("Gold CUI:", mention2gold[mention])
print("Predicted CUI:", pred_cui)

Batches: 100%|██████████| 1/1 [00:00<00:00, 36.35it/s]

(1, 768)
Mention ID: 9931324.1
Context: Missense mutations in the most ancient residues of the PAX6 paired domain underlie a spectrum of human [ENTITY_START] congenital eye malformations. [ENTITY_END] Mutations of the human PAX6 gene underlie aniridia (congenital absence of the iris), a rare dominant malformation of the eye. The spectrum of PAX6 mutations in aniridia patients is highly
Top k examples: Mention 1: aniridia || Context: Three novel [ENTITY_START] aniridia [ENTITY_END] mutations in the human PAX6 gene. Aniridia (iris hypoplasia) is an autosomal dominant congenital disorder of the eye. Mutations in the human aniridia (PAX6) gene have now been identified in many || Correct CUI: {'MESH:D015783': {'cui': 'MESH:D015783', 'name': 'Aniridia', 'types': 'Disease', 'aliases': 'Absent Iris|AN|AN1|AN2|AN3|ANIRIDIA 1|ANIRIDIA 2|ANIRIDIA 3|ANIRIDIA II, FORMERLY;AN2, FORMERLY CATARACT, CONGENITAL, WITH LATE-ONSET CORNEAL DYSTROPHY, INCLUDED|Congenital Aniridia|Irideremia', 'definition': 'A congenital abnormality in which there is only a rudimentary iris. This is due to the failure of the optic cup to grow. Aniridia also occurs in a hereditary form, usually autosomal dominant.'}}
Mention 2: iris hypoplasia || Context: PAX6 mutations in aniridia. Aniridia is a congenital malformation of the eye, chiefly characterised by [ENTITY_START] iris hypoplasia, [ENTITY_END] which can cause blindness. The PAX6 gene was isolated as a candidate aniridia gene by positional cloning from the smallest region of overlap of aniridia-associated deletions. Subsequently PAX6 intragenic mutations were || Correct CUI: {'MESH:D007499': {'cui': 'MESH:D007499', 'name': 'Iris Diseases', 'types': 'Disease', 'aliases': 'Disease, Iris|Diseases, Iris|Iris Disease', 'definition': 'Diseases, dysfunctions, or disorders of or located in the iris.'}}
Mention 3: Aniridia || Context: Three novel aniridia mutations in the human PAX6 gene. [ENTITY_START] Aniridia [ENTITY_END] (iris hypoplasia) is an autosomal dominant congenital disorder of the eye. Mutations in the human aniridia (PAX6) gene have now been identified in many patients from various ethnic groups. In the || Correct CUI: {'MESH:D015783': {'cui': 'MESH:D015783', 'name': 'Aniridia', 'types': 'Disease', 'aliases': 'Absent Iris|AN|AN1|AN2|AN3|ANIRIDIA 1|ANIRIDIA 2|ANIRIDIA 3|ANIRIDIA II, FORMERLY;AN2, FORMERLY CATARACT, CONGENITAL, WITH LATE-ONSET CORNEAL DYSTROPHY, INCLUDED|Congenital Aniridia|Irideremia', 'definition': 'A congenital abnormality in which there is only a rudimentary iris. This is due to the failure of the optic cup to grow. Aniridia also occurs in a hereditary form, usually autosomal dominant.'}}
Text: congenital eye malformations
Gold CUI: ['MESH:D005124']
Predicted CUI:  MESH:D005124

In [44]:
# def evaluate_vllm_aqlm(
#     llm,
#     nlp_model,
#     tokenizer,
#     index,
#     system_instructions,
#     mentions,
#     ontology,
#     corpus,
#     mention2context,
#     mention2biencoder_candidates,
#     mention2text,
#     TrainMap_context2mention,
#     train_mention2text,
#     train_mention2gold,
#     k,
#     sampling_params,
# ):
#     """
#     Run "prompt" function for each mention in the list of mentions.
#     Returns a dictionary {mention_id : predicted CUI}
#     -------
#     llm : LLM model
#     nlp_model : SentenceTransformer model
#     tokenizer : AutoTokenizer
#     index : faiss index
#     system_instructions : str (instructions for the LLM)
#     mentions : list (mention_ids)
#     ontology : BiomedicalOntology object
#     corpus : list of str (all context sentences)
#     mention2context : dict (mention_id : context)
#     mention2biencoder_candidates : dict (mention_id : list of candidate CUIs)
#     mention2text : dict (mention_id : mention name)
#     TrainMap_context2mention : dict (context sentence to mention_id)
#     train_mention2text : dict (mention_id to mention name)
#     train_mention2gold : dict (mention_id to gold CUI)
#     k : int (number of nearest neighbors)
#     sampling_params : SamplingParams config
#     """
#     results = {}
#     for i in range(len(mentions)) :
#         mention_id = mentions[i]
#         mention_name = mention2text[mention_id]
#         context = mention2context[mention_id]
#         candidates = get_candidates_data(mention2biencoder_candidates[mentions[i]], ontology)
#         # candidates = get_candidates_data_v2(mention2crossencoder_candidates[mention])
#         topk = topk_examples(
#             model=nlp_model,  # sentence transformer model
#             index=index,
#             query=context,
#             corpus=corpus,
#             TrainMap_context2mention=TrainMap_context2mention,
#             train_mention2text=train_mention2text,
#             train_mention2gold=train_mention2gold,
#             ontology=ontology,
#             k=k,
#         )
#         text = prompt_vllm_aqlm(
#             mention=mention_name,
#             context=context,
#             system_instructions=system_instructions,
#             candidates=candidates,
#             topk_examples=topk,
#             llm=llm,
#             tokenizer=tokenizer,
#             sampling_params=sampling_params,
#         )
#         print("mention ID :", mention_id , "|| LLM answer :", text)
#         cand = extract_cui(text)
#         results[mention_id] = cand
#         if i%20 == 0:
#             print(f"i = {i}")

#     return results

In [46]:
results = evaluate_vllm_aqlm(llm=llm,
                        nlp_model=model,
                        tokenizer=tokenizer,
                        index=index,
                        system_instructions=system_instructions,
                        mentions=mentions[:5],
                        ontology=ontology2,
                        corpus=corpus,
                        mention2context=mention2context,
                        mention2biencoder_candidates=mention2biencoder_candidates,
                        mention2text=mention2text,
                        TrainMap_context2mention=TrainMap_context2mention,
                        train_mention2text=train_mention2text,
                        train_mention2gold=train_mention2gold,
                        k=10,
                        sampling_params=sampling_params)
results

Batches: 100%|██████████| 1/1 [00:00<00:00, 97.73it/s]

(1, 768)
mention ID : 9288106.1 || LLM answer :  MESH:D001260
i = 0

Batches: 100%|██████████| 1/1 [00:00<00:00, 87.08it/s]

(1, 768)

mention ID : 9288106.2 || LLM answer :  'MESH:D016399'

Batches: 100%|██████████| 1/1 [00:00<00:00, 87.14it/s]

(1, 768)

mention ID : 9288106.3 || LLM answer :  MESH:D001260

Batches: 100%|██████████| 1/1 [00:00<00:00, 93.94it/s]

(1, 768)

mention ID : 9288106.4 || LLM answer :  MESH:D001260

Batches: 100%|██████████| 1/1 [00:00<00:00, 107.52it/s]

(1, 768)

mention ID : 9288106.5 || LLM answer :  MESH:D030342

{'9288106.1': 'MESH:D001260',
 '9288106.2': 'MESH:D016399',
 '9288106.3': 'MESH:D001260',
 '9288106.4': 'MESH:D001260',
 '9288106.5': 'MESH:D030342'}

In [47]:
results

{'9288106.1': 'MESH:D001260',
 '9288106.2': 'MESH:D016399',
 '9288106.3': 'MESH:D001260',
 '9288106.4': 'MESH:D001260',
 '9288106.5': 'MESH:D030342'}

In [49]:
score = scoring(results=results, mention2gold=mention2gold)
score

0.8

### Fine-tuning

In [37]:
from datasets import load_metric

bleu = load_metric("bleu")

prediction1 = [["there", "is", "a", "need", "for", "adequate", "and", "predictable", "resources"]]
prediction2 = [["resources", "be", "sufficient", "and", "predictable", "to"]] 

reference1 = [[["resources", "have", "to", "be", "sufficient", "and", "they", "have", "to", "be", "predictable"]]]
reference2 = [[["adequate", "and", "predictable", "resources", "are", "required"]]]

bleu_c1r1 = bleu.compute(predictions=prediction1, references=reference1, max_order=2)
print("bleu score for c1 using r1 :", bleu_c1r1)
bleu_c1r2 = bleu.compute(predictions=prediction1, references=reference2, max_order=2)
print("bleu score for c1 using r2 :", bleu_c1r2)

bleu_c2r1 = bleu.compute(predictions=prediction2, references=reference1, max_order=2)
print("bleu score for c2 using r1 :", bleu_c2r1)
bleu_c2r2 = bleu.compute(predictions=prediction2, references=reference1, max_order=2)
print("bleu score for c2 using r2 :", bleu_c2r2)

/nethome/cye73/conda_envs/bioel/lib/python3.9/site-packages/datasets/load.py:756: FutureWarning: The repository for bleu contains custom code which must be executed to correctly load the metric. You can inspect the repository content at https://raw.githubusercontent.com/huggingface/datasets/2.18.0/metrics/bleu/bleu.py
You can avoid this message in future by passing the argument `trust_remote_code=True`.
Passing `trust_remote_code=True` will be mandatory to load this metric from the next major release of `datasets`.
  warnings.warn(

bleu score for p1 using r1 : {'bleu': 0.0, 'precisions': [0.3333333333333333, 0.0], 'brevity_penalty': 0.8007374029168082, 'length_ratio': 0.8181818181818182, 'translation_length': 9, 'reference_length': 11}
bleu score for p1 using r2 : {'bleu': 0.408248290463863, 'precisions': [0.4444444444444444, 0.375], 'brevity_penalty': 1.0, 'length_ratio': 1.5, 'translation_length': 9, 'reference_length': 6}
bleu score for p2 using r1 : {'bleu': 0.2748640411822265, 'precisions': [1.0, 0.4], 'brevity_penalty': 0.43459820850707814, 'length_ratio': 0.5454545454545454, 'translation_length': 6, 'reference_length': 11}
bleu score for p2 using r2 : {'bleu': 0.2748640411822265, 'precisions': [1.0, 0.4], 'brevity_penalty': 0.43459820850707814, 'length_ratio': 0.5454545454545454, 'translation_length': 6, 'reference_length': 11}

In [38]:
prediction1 = [["there", "is", "a", "need", "for", "adequate", "and", "predictable", "resources"]]
prediction2 = [["resources", "be", "sufficient", "and", "predictable", "to"]] 

reference1 = [[["resources", "have", "to", "be", "sufficient", "and", "they", "have", "to", "be", "predictable"]], [["adequate", "and", "predictable", "resources", "are", "required"]]]
# reference2 = [[["adequate", "and", "predictable", "resources", "are", "required"]]]

bleu_c1r1 = bleu.compute(predictions=prediction1, references=reference1, max_order=2)
print("bleu score for c1 using r1 :", bleu_c1r1)


bleu_c2r1 = bleu.compute(predictions=prediction2, references=reference1, max_order=2)
print("bleu score for c2 using r1 :", bleu_c2r1)

ValueError: Mismatch in the number of predictions (1) and references (2)